from pathlib import Path
import re

path = Path('RoutePilotStandalone/app/src/main/java/com/routepilot/app/RoutePilotProActivity.java')
s = path.read_text()


def rep(old, new, label):
    global s
    if old not in s:
        raise SystemExit(f'missing replacement: {label}')
    s = s.replace(old, new, 1)


def sub(pattern, replacement, label):
    global s
    ns, n = re.subn(pattern, replacement, s, count=1, flags=re.S)
    if n != 1:
        raise SystemExit(f'missing regex replacement: {label} ({n})')
    s = ns


rep('private Polyline liveTrack,previewTrack,approachTrack;', 'private Polyline liveTrack,previewTrack,approachTrack;\n    private Marker previewCursor;', 'preview cursor field')
rep('private View topBar,recordSheet,dock,page,planSheet,focusRestore,guidanceHud;', 'private View topBar,recordSheet,dock,page,planSheet,focusRestore,guidanceHud,planLegend;', 'plan legend field')
rep('private boolean recording,paused,collapsed,focusMode,guiding,guidanceCameraFollow=true,approachingStart;', 'private boolean recording,paused,collapsed,focusMode,guiding,guidanceCameraFollow=true,recordingCameraFollow=true,approachingStart;', 'recording follow field')
rep('private TextView guideTitle,guideSubtitle,guideProgress,guideRemaining,guideNext,guideDeviation;', 'private TextView guideTitle,guideSubtitle,guideProgress,guideRemaining,guideNext,guideDeviation,guideEventAlert;', 'guide alert field')
rep('private RouteStore.Summary previewSummary;', 'private RouteStore.Summary previewSummary;\n    private String lastEventAlertKey="";', 'event alert key')
rep('        if(prefs.getBoolean("compact_ui",false))setCollapsed(true);\n', '        prefs.edit().remove("compact_ui").remove("reduce_motion").apply();\n', 'legacy settings cleanup')
rep('map.setOnTouchListener((v,e)->{if(guiding&&e.getActionMasked()==MotionEvent.ACTION_DOWN)guidanceCameraFollow=false;return false;});', 'map.setOnTouchListener((v,e)->{if(e.getActionMasked()==MotionEvent.ACTION_DOWN){if(guiding)guidanceCameraFollow=false;if(recording)recordingCameraFollow=false;}return false;});', 'manual map camera')
rep('plus.setOnClickListener(v->openNewRecording());', 'plus.setOnClickListener(v->{press(v);showToursActionSheet();});', 'tours plus')

sub(r'    private void routeMenu\(RouteStore\.Summary s\)\{.*?\n    \}\n\n    private void openPlan', '''    private void routeMenu(RouteStore.Summary s){
        Dialog d=new Dialog(this);FrameLayout shell=new FrameLayout(this);shell.setPadding(dp(14),0,dp(14),dp(14));LinearLayout panel=sheetPanel(store.displayName(s.file),formatDuration(s.durationMs)+" • "+formatDistance(s.distanceM));
        String[] labels={"▣  Voir le plan","▶  Démarrer la tournée","✎  Renommer","↗  Exporter / partager","⧉  Dupliquer",store.isFavorite(s.file)?"☆  Retirer des favoris":"★  Ajouter aux favoris","⌫  Supprimer"};
        for(int i=0;i<labels.length;i++){final int index=i;TextView action=sheetAction(labels[i],i==6?Color.argb(120,255,69,58):Color.argb(48,255,255,255));action.setOnClickListener(v->{press(v);d.dismiss();root.postDelayed(()->{if(index==0)openPlan(s);else if(index==1)chooseGuidanceDirection(s);else if(index==2)rename(s.file);else if(index==3)share(s.file);else if(index==4){if(store.duplicate(s.file)!=null){toast("Tournée dupliquée");showHistory();}}else if(index==5){store.setFavorite(s.file,!store.isFavorite(s.file));showHistory();}else deleteRoute(s.file);},130);});panel.addView(action,bottom(7));}
        presentBottomSheet(d,shell,panel);
    }

    private void openPlan''', 'modern route menu')

rep('TextView close=circle("×",GLASS2);close.setOnClickListener(v->closePlan());head.addView(close,new LinearLayout.LayoutParams(dp(40),dp(40)));', 'TextView close=pill("Fermer",Color.argb(70,255,255,255),11);close.setOnClickListener(v->{press(v);closePlan();});head.addView(close,new LinearLayout.LayoutParams(dp(68),dp(40)));', 'plan close control')

sub(r'    private void drawSummary\(RouteStore\.Summary s,boolean reverse\)\{.*?\n    \}\n\n    private void fitSummary', '''    private void drawSummary(RouteStore.Summary s,boolean reverse){
        clearPreview();previewTrack=new Polyline();previewTrack.getOutlinePaint().setColor(traceColor());previewTrack.getOutlinePaint().setStrokeWidth(dp(9));previewTrack.getOutlinePaint().setStrokeCap(Paint.Cap.ROUND);List<GeoPoint> pts=new ArrayList<>();if(reverse){for(int i=s.points.size()-1;i>=0;i--)pts.add(new GeoPoint(s.points.get(i).lat,s.points.get(i).lon));}else for(RouteStore.Point p:s.points)pts.add(new GeoPoint(p.lat,p.lon));previewTrack.setPoints(pts);map.getOverlays().add(previewTrack);addMarker(pts.get(0),"D",GREEN,"preview");for(RouteStore.Event e:s.events){String badge="REVERSE".equals(e.type)?"MA":"2C";addMarker(new GeoPoint(e.lat,e.lon),badge,"REVERSE".equals(e.type)?ORANGE:CYAN,"preview-event");}addMarker(pts.get(pts.size()-1),"A",RED,"preview");fitSummary(s);map.invalidate();
    }

    private void fitSummary''', 'semantic plan markers')

rep('private void enterPlanOverview(RouteStore.Summary s){stopPreviewPlayback();enterFocusMode();map.postDelayed(()->fitSummary(s),130);}', 'private void enterPlanOverview(RouteStore.Summary s){stopPreviewPlayback();enterFocusMode();showPlanLegend();map.postDelayed(()->fitSummary(s),130);}', 'plan overview legend')
rep('private void enterPlanPreview(RouteStore.Summary s){enterFocusMode();startPreviewPlayback(s);}', 'private void enterPlanPreview(RouteStore.Summary s){removePlanLegend();enterFocusMode();startPreviewPlayback(s);}', 'preview legend cleanup')

sub(r'    private void startPreviewPlayback\(RouteStore\.Summary s\)\{.*?\n    \}\n    private void stopPreviewPlayback\(\)\{.*?\n', '''    private void startPreviewPlayback(RouteStore.Summary s){
        stopPreviewPlayback();if(s.points.isEmpty())return;previewSummary=s;previewIndex=0;RouteStore.Point first=s.points.get(0);previewCursor=new Marker(map);previewCursor.setPosition(new GeoPoint(first.lat,first.lon));previewCursor.setAnchor(.5f,.5f);previewCursor.setIcon(marker("◆",accent()));previewCursor.setRelatedObject("preview-cursor");map.getOverlays().add(previewCursor);toast("Aperçu animé • suis le repère lumineux");int step=Math.max(1,s.points.size()/150);previewRunnable=new Runnable(){@Override public void run(){if(previewSummary==null||previewIndex>=previewSummary.points.size()){stopPreviewPlayback();return;}RouteStore.Point p=previewSummary.points.get(previewIndex);if(previewCursor!=null){previewCursor.setPosition(new GeoPoint(p.lat,p.lon));previewCursor.setIcon(marker(previewIndex%2==0?"◆":"●",accent()));}map.getController().animateTo(new GeoPoint(p.lat,p.lon));if(previewIndex==0)map.getController().setZoom(17.4);map.invalidate();previewIndex+=step;previewTimer.postDelayed(this,150);}};previewTimer.post(previewRunnable);
    }
    private void stopPreviewPlayback(){if(previewRunnable!=null)previewTimer.removeCallbacks(previewRunnable);previewRunnable=null;previewSummary=null;if(previewCursor!=null){map.getOverlays().remove(previewCursor);previewCursor=null;map.invalidate();}}
''', 'preview cursor playback')

rep('guiding=true;guidingRoute=s;guidingReverse=reverse;guidanceCameraFollow=true;drawSummary(s,reverse);', 'guiding=true;guidingRoute=s;guidingReverse=reverse;guidanceCameraFollow=true;lastEventAlertKey="";drawSummary(s,reverse);makeGuidanceEventsSubtle();', 'guidance subtle markers')
rep('        FrameLayout layer=new FrameLayout(this);layer.setClickable(false);\n', '        FrameLayout layer=new FrameLayout(this);layer.setClickable(false);\n        guideEventAlert=pill("",Color.argb(225,255,159,10),13);guideEventAlert.setVisibility(View.GONE);guideEventAlert.setElevation(dp(24));FrameLayout.LayoutParams alertP=new FrameLayout.LayoutParams(-1,dp(54),Gravity.TOP);alertP.setMargins(dp(18),safeTop()+dp(92),dp(18),0);layer.addView(guideEventAlert,alertP);\n', 'guidance alert view')
rep('GuidanceEngine.State s=guidance.update(l.getLatitude(),l.getLongitude());guideProgress.setText(s.progressPercent+" %");guideRemaining.setText(formatDistance(s.remainingM));guideDeviation.setText(Math.round(s.distanceToTraceM)+" m");', 'GuidanceEngine.State s=guidance.update(l.getLatitude(),l.getLongitude());if(s.nextEvent!=null&&s.distanceToNextEventM<=60)showEventAlert(s.nextEvent.type,s.nextEvent.label);else hideEventAlert();guideProgress.setText(s.progressPercent+" %");guideRemaining.setText(formatDistance(s.remainingM));guideDeviation.setText(Math.round(s.distanceToTraceM)+" m");', 'guidance event proximity')
rep('private void stopGuidance(){guiding=false;guidanceCameraFollow=true;approachingStart=false;clearApproachRoute();guidance=null;guidingRoute=null;if(guidanceHud!=null){root.removeView(guidanceHud);guidanceHud=null;}clearPreview();showHistory();}', 'private void stopGuidance(){guiding=false;guidanceCameraFollow=true;approachingStart=false;clearApproachRoute();guidance=null;guidingRoute=null;guideEventAlert=null;lastEventAlertKey="";if(guidanceHud!=null){root.removeView(guidanceHud);guidanceHud=null;}clearPreview();showHistory();}', 'guidance cleanup')

rep('c.addView(section("APPARENCE"));c.addView(choice("Couleur d’accent",prefs.getString("accent","Bleu"),v->accentDialog()),bottom(9));c.addView(choice("Couleur de la trace",prefs.getString("trace_color","Orange"),v->traceColorDialog()),bottom(9));c.addView(toggle("Interface compacte","Replie le panneau d’enregistrement au démarrage","compact_ui",false),bottom(9));c.addView(toggle("Animations réduites","Diminue les transitions visuelles","reduce_motion",false),bottom(9));', 'c.addView(section("APPARENCE"));c.addView(choice("Couleur d’accent",prefs.getString("accent","Bleu"),v->accentDialog()),bottom(9));c.addView(choice("Couleur de la trace",prefs.getString("trace_color","Orange"),v->traceColorDialog()),bottom(9));', 'remove obsolete settings rows')

rep('store.clearDraft();recording=true;paused=false;', 'store.clearDraft();recording=true;recordingCameraFollow=true;paused=false;', 'recording camera state')
rep('if(prefs.getBoolean("follow",true))map.getController().animateTo(g.get(g.size()-1));', 'if(recordingCameraFollow&&prefs.getBoolean("follow",true))map.getController().animateTo(g.get(g.size()-1));', 'recording manual camera')
rep('private void recenter(){if(lastLocation==null){toast("Position GPS en attente");return;}if(guiding)guidanceCameraFollow=true;map.getController().animateTo(new GeoPoint(lastLocation.getLatitude(),lastLocation.getLongitude()));map.getController().setZoom(guiding?17.8:18.6);}', 'private void recenter(){if(lastLocation==null){toast("Position GPS en attente");return;}if(guiding)guidanceCameraFollow=true;if(recording)recordingCameraFollow=true;map.getController().animateTo(new GeoPoint(lastLocation.getLatitude(),lastLocation.getLongitude()));if(guiding)map.getController().setZoom(17.4);else if(!recording)map.getController().setZoom(18.2);}', 'recenter without recording zoom')

rep('events.add(e);addMarker(new GeoPoint(e.lat,e.lon),String.valueOf(events.size()),color,"live");', 'events.add(e);addSubtleMarker(new GeoPoint(e.lat,e.lon),color,"live");', 'subtle live add event')
s = s.replace('addMarker(new GeoPoint(e.lat,e.lon),String.valueOf(i+1),"REVERSE".equals(e.type)?ORANGE:GREEN,"live");', 'addSubtleMarker(new GeoPoint(e.lat,e.lon),"REVERSE".equals(e.type)?ORANGE:CYAN,"live");')

sub(r'    private void showFinishSummary\(RouteStore\.Summary s\)\{.*?\n    \}\n\n    private void togglePause', '''    private void showFinishSummary(RouteStore.Summary s){
        Dialog d=new Dialog(this);FrameLayout shell=new FrameLayout(this);shell.setPadding(dp(14),0,dp(14),dp(14));LinearLayout panel=sheetPanel("Tournée enregistrée",formatDuration(s.durationMs)+" • "+formatDistance(s.distanceM)+" • "+s.events.size()+" repères");EditText name=new EditText(this);name.setSingleLine(true);name.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);name.setText(store.displayName(s.file));name.setSelectAllOnFocus(true);name.setTextColor(Color.WHITE);name.setHintTextColor(MUTED);name.setTextSize(16);name.setPadding(dp(15),0,dp(15),0);name.setBackground(glass(Color.argb(65,255,255,255),18));panel.addView(name,new LinearLayout.LayoutParams(-1,dp(54)));TextView save=sheetAction("✓  Enregistrer le nom",accent());save.setOnClickListener(v->{press(v);store.rename(s.file,name.getText().toString());d.dismiss();toast("Nom enregistré");});panel.addView(save,top(10));TextView plan=sheetAction("▣  Voir le plan",Color.argb(65,255,255,255));plan.setOnClickListener(v->{press(v);store.rename(s.file,name.getText().toString());d.dismiss();root.postDelayed(()->openPlan(store.parse(s.file)),130);});panel.addView(plan,top(7));TextView later=sheetAction("Plus tard",Color.argb(35,255,255,255));later.setOnClickListener(v->d.dismiss());panel.addView(later,top(7));presentBottomSheet(d,shell,panel);
    }

    private void togglePause''', 'modern finish sheet')

insert = '''
    private LinearLayout sheetPanel(String title,String subtitle){LinearLayout panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(dp(18),dp(8),dp(18),dp(18));panel.setBackground(glass(Color.argb(248,20,22,29),30));TextView handle=text("—",28,Typeface.BOLD,Color.argb(90,255,255,255));handle.setGravity(Gravity.CENTER);panel.addView(handle,new LinearLayout.LayoutParams(-1,dp(26)));panel.addView(text(title,22,Typeface.BOLD,Color.WHITE));if(subtitle!=null&&!subtitle.isEmpty()){TextView sub=text(subtitle,11,Typeface.NORMAL,MUTED);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,-2);sp.topMargin=dp(4);sp.bottomMargin=dp(14);panel.addView(sub,sp);}return panel;}
    private TextView sheetAction(String label,int color){TextView v=pill(label,color,13);v.setGravity(Gravity.CENTER_VERTICAL);v.setPadding(dp(16),0,dp(16),0);return v;}
    private void presentBottomSheet(Dialog d,FrameLayout shell,LinearLayout panel){shell.addView(panel,new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM));d.setContentView(shell);setBackdropBlur(true);d.setOnDismissListener(x->setBackdropBlur(false));d.show();android.view.Window w=d.getWindow();if(w!=null){w.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));w.setLayout(-1,-2);w.setGravity(Gravity.BOTTOM);w.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);WindowManager.LayoutParams a=w.getAttributes();a.dimAmount=.48f;w.setAttributes(a);}panel.setAlpha(0);panel.setTranslationY(dp(34));panel.setScaleX(.985f);panel.setScaleY(.985f);panel.animate().alpha(1).translationY(0).scaleX(1).scaleY(1).setDuration(300).setInterpolator(new DecelerateInterpolator()).start();}
    private void showToursActionSheet(){Dialog d=new Dialog(this);FrameLayout shell=new FrameLayout(this);shell.setPadding(dp(14),0,dp(14),dp(14));LinearLayout panel=sheetPanel("Tournées","Créer, importer ou exporter une tournée");TextView fresh=sheetAction("＋  Nouvelle tournée",accent());fresh.setOnClickListener(v->{press(v);d.dismiss();root.postDelayed(this::openNewRecording,130);});panel.addView(fresh,bottom(8));TextView imp=sheetAction("⇩  Importer une tournée GPX",Color.argb(62,255,255,255));imp.setOnClickListener(v->{press(v);d.dismiss();root.postDelayed(this::importGpx,130);});panel.addView(imp,bottom(8));TextView exp=sheetAction("⇧  Exporter une tournée",Color.argb(62,255,255,255));exp.setOnClickListener(v->{press(v);d.dismiss();root.postDelayed(this::showExportRoutePicker,130);});panel.addView(exp,bottom(8));TextView cancel=sheetAction("Fermer",Color.argb(30,255,255,255));cancel.setOnClickListener(v->d.dismiss());panel.addView(cancel);presentBottomSheet(d,shell,panel);}
    private void showExportRoutePicker(){List<RouteStore.Summary> routes=store.summaries();if(routes.isEmpty()){toast("Aucune tournée à exporter");return;}Dialog d=new Dialog(this);FrameLayout shell=new FrameLayout(this);shell.setPadding(dp(14),0,dp(14),dp(14));LinearLayout panel=sheetPanel("Exporter une tournée","Choisis le plan GPX à partager ou enregistrer ailleurs");ScrollView sc=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);for(RouteStore.Summary r:routes){TextView a=sheetAction("↗  "+store.displayName(r.file),Color.argb(52,255,255,255));a.setOnClickListener(v->{press(v);d.dismiss();root.postDelayed(()->share(r.file),130);});list.addView(a,bottom(7));}sc.addView(list);panel.addView(sc,new LinearLayout.LayoutParams(-1,Math.min(dp(360),dp(64)*routes.size())));presentBottomSheet(d,shell,panel);}
    private void showPlanLegend(){removePlanLegend();LinearLayout legend=new LinearLayout(this);legend.setOrientation(LinearLayout.VERTICAL);legend.setPadding(dp(13),dp(10),dp(13),dp(10));legend.setBackground(glass(Color.argb(225,18,20,26),20));legend.addView(text("LÉGENDE DU PLAN",9,Typeface.BOLD,accent()));legend.addView(text("D  Départ   •   A  Arrivée",11,Typeface.BOLD,Color.WHITE),top(4));legend.addView(text("MA  Marche arrière   •   2C  Deux côtés",11,Typeface.BOLD,Color.WHITE),top(3));planLegend=legend;FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(-2,-2,Gravity.TOP|Gravity.START);lp.setMargins(dp(14),safeTop()+dp(8),0,0);root.addView(planLegend,lp);fade(planLegend);}
    private void removePlanLegend(){if(planLegend!=null){root.removeView(planLegend);planLegend=null;}}
    private void addSubtleMarker(GeoPoint p,int color,String tag){Marker m=new Marker(map);m.setPosition(p);m.setAnchor(.5f,.5f);m.setIcon(subtleMarker(color));m.setRelatedObject(tag);map.getOverlays().add(m);}
    private BitmapDrawable subtleMarker(int color){int z=dp(16);Bitmap b=Bitmap.createBitmap(z,z,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(b);Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);p.setColor(Color.argb(75,Color.red(color),Color.green(color),Color.blue(color)));c.drawCircle(z/2f,z/2f,z*.32f,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(1));p.setColor(Color.argb(110,255,255,255));c.drawCircle(z/2f,z/2f,z*.32f,p);return new BitmapDrawable(getResources(),b);}
    private void makeGuidanceEventsSubtle(){for(org.osmdroid.views.overlay.Overlay o:map.getOverlays())if(o instanceof Marker&&"preview-event".equals(((Marker)o).getRelatedObject()))((Marker)o).setIcon(subtleMarker(accent()));map.invalidate();}
    private void showEventAlert(String type,String label){if(guideEventAlert==null)return;String key=type+"|"+label;if(!key.equals(lastEventAlertKey)){lastEventAlertKey=key;guideEventAlert.setText(("REVERSE".equals(type)?"↶  MARCHE ARRIÈRE":"⇆  2 CÔTÉS")+"  •  maintenant");guideEventAlert.setBackground(glass("REVERSE".equals(type)?Color.argb(235,255,159,10):Color.argb(235,100,210,255),20));guideEventAlert.setVisibility(View.VISIBLE);guideEventAlert.setAlpha(0);guideEventAlert.setTranslationY(-dp(10));guideEventAlert.animate().alpha(1).translationY(0).setDuration(220).setInterpolator(new OvershootInterpolator(.65f)).start();haptic(guideEventAlert);}else if(guideEventAlert.getVisibility()!=View.VISIBLE)guideEventAlert.setVisibility(View.VISIBLE);}
    private void hideEventAlert(){lastEventAlertKey="";if(guideEventAlert!=null&&guideEventAlert.getVisibility()==View.VISIBLE)guideEventAlert.animate().alpha(0).translationY(-dp(8)).setDuration(160).withEndAction(()->{if(guideEventAlert!=null)guideEventAlert.setVisibility(View.GONE);}).start();}
'''
anchor = '    private void accentDialog(){'
if anchor not in s:
    raise SystemExit('missing helper insertion anchor')
s = s.replace(anchor, insert + '\n' + anchor, 1)

rep('private void exitFocusMode(){focusMode=false;if(focusRestore!=null){root.removeView(focusRestore);focusRestore=null;}', 'private void exitFocusMode(){focusMode=false;removePlanLegend();if(focusRestore!=null){root.removeView(focusRestore);focusRestore=null;}', 'focus legend cleanup')
rep('private void clearPreview(){if(previewTrack!=null){map.getOverlays().remove(previewTrack);previewTrack=null;}map.getOverlays().removeIf(o->o instanceof Marker&&"preview".equals(((Marker)o).getRelatedObject()));map.invalidate();}', 'private void clearPreview(){if(previewTrack!=null){map.getOverlays().remove(previewTrack);previewTrack=null;}map.getOverlays().removeIf(o->o instanceof Marker&&((Marker)o).getRelatedObject() instanceof String&&((String)((Marker)o).getRelatedObject()).startsWith("preview"));previewCursor=null;map.invalidate();}', 'preview cleanup')
rep('private void fade(View v){if(prefs.getBoolean("reduce_motion",false)){v.setAlpha(1);return;}v.setAlpha(0);v.setScaleX(.985f);v.setScaleY(.985f);v.setTranslationY(dp(14));v.animate().alpha(1).scaleX(1).scaleY(1).translationY(0).setDuration(320).setInterpolator(new DecelerateInterpolator()).start();}', 'private void fade(View v){v.setAlpha(0);v.setScaleX(.985f);v.setScaleY(.985f);v.setTranslationY(dp(14));v.animate().alpha(1).scaleX(1).scaleY(1).translationY(0).setDuration(320).setInterpolator(new DecelerateInterpolator()).start();}', 'always animate')

path.write_text(s)
