package com.routepilot.app;

import android.animation.ValueAnimator;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.view.WindowManager;
import android.view.animation.DecelerateInterpolator;
import android.view.animation.OvershootInterpolator;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.appcompat.app.AppCompatActivity;

public class OnboardingActivity extends AppCompatActivity {
    private static final int BG=Color.rgb(7,8,12),BLUE=Color.rgb(10,132,255),CYAN=Color.rgb(82,210,255),GLASS=Color.argb(178,31,34,44),MUTED=Color.argb(184,255,255,255);
    private SharedPreferences prefs; private FrameLayout root; private LinearLayout pageHost,dots; private TextView action; private int step=0; private boolean locationConsent,dataConsent;
    @Override protected void onCreate(Bundle state){super.onCreate(state);prefs=getSharedPreferences("routepilot",MODE_PRIVATE);if(prefs.getBoolean("onboarding_complete",false)){launchApp();return;}getWindow().setStatusBarColor(Color.TRANSPARENT);getWindow().setNavigationBarColor(BG);getWindow().addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);root=new FrameLayout(this);root.setBackground(background());addOrb(Color.rgb(25,112,255),320,Gravity.TOP|Gravity.END,5200);addOrb(Color.rgb(160,65,255),280,Gravity.BOTTOM|Gravity.START,6100);LinearLayout shell=new LinearLayout(this);shell.setOrientation(LinearLayout.VERTICAL);shell.setPadding(dp(20),dp(34),dp(20),dp(20));root.addView(shell,new FrameLayout.LayoutParams(-1,-1));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(dp(10),dp(8),dp(10),dp(8));top.setBackground(liquid(Color.argb(135,34,38,49),24));TextView mark=label("RP",15,Typeface.BOLD,Color.WHITE);mark.setGravity(Gravity.CENTER);mark.setBackground(liquid(BLUE,17));top.addView(mark,new LinearLayout.LayoutParams(dp(42),dp(42)));LinearLayout brand=new LinearLayout(this);brand.setOrientation(LinearLayout.VERTICAL);brand.addView(label("RoutePilot",18,Typeface.BOLD,Color.WHITE));brand.addView(label("Tournées terrain • données sous ton contrôle",9,Typeface.NORMAL,MUTED));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(0,-2,1);bp.leftMargin=dp(11);top.addView(brand,bp);TextView skip=label("Passer",12,Typeface.BOLD,MUTED);skip.setGravity(Gravity.CENTER);skip.setBackground(liquid(Color.argb(42,255,255,255),15));skip.setOnClickListener(v->{press(v);step=3;render();});top.addView(skip,new LinearLayout.LayoutParams(dp(68),dp(38)));shell.addView(top);pageHost=new LinearLayout(this);pageHost.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams ph=new LinearLayout.LayoutParams(-1,0,1);ph.topMargin=dp(25);shell.addView(pageHost,ph);dots=new LinearLayout(this);dots.setGravity(Gravity.CENTER);LinearLayout.LayoutParams dl=new LinearLayout.LayoutParams(-1,dp(24));dl.bottomMargin=dp(10);shell.addView(dots,dl);action=label("Continuer",16,Typeface.BOLD,Color.WHITE);action.setGravity(Gravity.CENTER);action.setBackground(liquid(BLUE,22));action.setOnClickListener(v->next());shell.addView(action,new LinearLayout.LayoutParams(-1,dp(58)));TextView version=label("RoutePilot 1.0.3 • stockage local • sans compte RoutePilot",10,Typeface.NORMAL,Color.argb(118,255,255,255));version.setGravity(Gravity.CENTER);LinearLayout.LayoutParams vp=new LinearLayout.LayoutParams(-1,-2);vp.topMargin=dp(12);shell.addView(version,vp);setContentView(root);render();}
    private void render(){pageHost.animate().alpha(0).translationX(-dp(16)).scaleX(.985f).scaleY(.985f).setDuration(120).withEndAction(()->{pageHost.removeAllViews();pageHost.setAlpha(0);pageHost.setTranslationX(dp(22));if(step==0)intro();else if(step==1)features();else if(step==2)offline();else if(step==3)privacy();else consent();pageHost.animate().alpha(1).translationX(0).scaleX(1).scaleY(1).setDuration(330).setInterpolator(new DecelerateInterpolator()).start();dots();}).start();}
    private void intro(){hero("⌁","La tournée, sans le chaos.","Enregistre précisément ton parcours réel, mémorise les actions métier et rejoue la tournée plus tard avec une interface pensée pour le terrain.");card("Trace GPS fidèle","Les points sont stockés avec leur précision et leur heure.");action.setText("Découvrir RoutePilot");enable(true);}
    private void features(){hero("◎","Ton trajet devient un guide","Marche arrière et 2 côtés sont enregistrés exactement là où tu les déclenches, puis réapparaissent au bon moment pendant le guidage.");card("↶  Marche arrière","Repère géolocalisé et alerte à l’approche.");card("⇆  2 côtés","Repère métier discret sur la carte, clair dans le HUD.");card("▶  Relecture visuelle","La trace enregistrée reste la référence, sans navigation vocale.");action.setText("Continuer");enable(true);}
    private void offline(){hero("▧","Online ou hors ligne","OpenStreetMap sert de fond en ligne. Les packs vectoriels français peuvent rester sur le téléphone pour travailler sans réseau.");card("Cartes séparées de l’APK","Télécharge uniquement les zones utiles depuis Réglages.");card("Tournées locales","Les fichiers GPX restent dans le stockage privé de RoutePilot jusqu’à une action de partage.");action.setText("Voir la confidentialité");enable(true);}
    private void privacy(){hero("◉","Confidentialité, sans texte flou","Voici concrètement ce qui sort du téléphone et ce qui reste local dans cette V1.");privacyCard("Position précise","Utilisée quand RoutePilot est ouvert pour enregistrer et guider. Aucune permission de localisation en arrière-plan n’est demandée.",Color.rgb(48,209,88));privacyCard("Tournées & heures","GPX, repères métier et heures sont enregistrés localement. Ils ne sont exportés que lorsque tu déclenches une action de partage.",CYAN);privacyCard("Services réseau","En OSM en ligne, les requêtes de tuiles vont à OpenStreetMap. Pour rejoindre le départ, les coordonnées sont envoyées au routeur public OSRM afin de calculer cet itinéraire.",Color.rgb(191,90,242));privacyCard("Compte & cloud","Cette V1 n’intègre ni compte RoutePilot ni synchronisation cloud des tournées.",Color.rgb(48,209,88));action.setText("J’ai compris");enable(true);}
    private void consent(){hero("✓","Tu gardes le contrôle","Deux confirmations avant d’activer RoutePilot. Elles sont mémorisées localement sur cet appareil.");pageHost.addView(consentRow("Localisation précise","Utilisée pour enregistrer et guider une tournée.",true),lp());pageHost.addView(consentRow("Données & réseau","J’ai compris le stockage local, le partage manuel, OSM et OSRM.",false),lp());action.setText("Commencer avec RoutePilot");enable(locationConsent&&dataConsent);}
    private void hero(String icon,String title,String body){TextView orb=label(icon,35,Typeface.BOLD,Color.WHITE);orb.setGravity(Gravity.CENTER);orb.setBackground(liquid(Color.argb(118,10,132,255),34));pageHost.addView(orb,new LinearLayout.LayoutParams(dp(76),dp(76)));orb.setScaleX(.7f);orb.setScaleY(.7f);orb.setAlpha(0);orb.animate().scaleX(1).scaleY(1).alpha(1).setDuration(420).setInterpolator(new OvershootInterpolator(.9f)).start();TextView t=label(title,31,Typeface.BOLD,Color.WHITE);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(-1,-2);tp.topMargin=dp(25);pageHost.addView(t,tp);TextView b=label(body,14.5f,Typeface.NORMAL,MUTED);b.setLineSpacing(dp(5),1);LinearLayout.LayoutParams bl=new LinearLayout.LayoutParams(-1,-2);bl.topMargin=dp(12);bl.bottomMargin=dp(18);pageHost.addView(b,bl);}
    private void card(String title,String body){LinearLayout c=glassCard();c.addView(label(title,15,Typeface.BOLD,Color.WHITE));c.addView(label(body,12,Typeface.NORMAL,MUTED));pageHost.addView(c,lp());}
    private void privacyCard(String title,String body,int color){LinearLayout c=glassCard();TextView t=label("●  "+title,15,Typeface.BOLD,Color.WHITE);t.setCompoundDrawablePadding(dp(6));c.addView(t);TextView b=label(body,11.5f,Typeface.NORMAL,MUTED);b.setLineSpacing(dp(3),1);c.addView(b);pageHost.addView(c,lp());}
    private View consentRow(String title,String body,boolean loc){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(14),dp(13),dp(14),dp(13));r.setBackground(liquid(GLASS,20));TextView check=label("",16,Typeface.BOLD,Color.WHITE);check.setGravity(Gravity.CENTER);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(dp(30),dp(30));cp.rightMargin=dp(12);r.addView(check,cp);LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.addView(label(title,14,Typeface.BOLD,Color.WHITE));tx.addView(label(body,11,Typeface.NORMAL,MUTED));r.addView(tx,new LinearLayout.LayoutParams(0,-2,1));Runnable paint=()->{boolean on=loc?locationConsent:dataConsent;check.setText(on?"✓":"");check.setBackground(liquid(on?BLUE:Color.argb(65,255,255,255),99));};paint.run();r.setOnClickListener(v->{press(v);if(loc)locationConsent=!locationConsent;else dataConsent=!dataConsent;paint.run();enable(locationConsent&&dataConsent);});return r;}
    private LinearLayout glassCard(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(15),dp(13),dp(15),dp(13));c.setBackground(liquid(GLASS,21));return c;} private LinearLayout.LayoutParams lp(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(8);return p;}
    private void dots(){dots.removeAllViews();for(int i=0;i<5;i++){View d=new View(this);d.setBackground(liquid(i==step?BLUE:Color.argb(55,255,255,255),99));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(i==step?25:7),dp(7));p.setMargins(dp(4),0,dp(4),0);dots.addView(d,p);}}
    private void next(){press(action);if(step<4){step++;render();return;}if(!action.isEnabled())return;prefs.edit().putBoolean("onboarding_complete",true).putBoolean("privacy_notice_seen",true).putBoolean("location_usage_accepted",true).apply();root.animate().alpha(0).scaleX(1.015f).scaleY(1.015f).setDuration(260).withEndAction(this::launchApp).start();}
    private void enable(boolean on){action.setEnabled(on);action.animate().alpha(on?1:.35f).setDuration(150).start();} private void launchApp(){startActivity(new Intent(this,RoutePilotProActivity.class));finish();overridePendingTransition(android.R.anim.fade_in,android.R.anim.fade_out);} private void press(View v){v.animate().scaleX(.965f).scaleY(.965f).setDuration(70).withEndAction(()->v.animate().scaleX(1).scaleY(1).setDuration(200).setInterpolator(new OvershootInterpolator(.7f)).start()).start();}
    private void addOrb(int color,int sizeDp,int gravity,long duration){View o=new View(this);GradientDrawable g=new GradientDrawable();g.setShape(GradientDrawable.OVAL);g.setGradientType(GradientDrawable.RADIAL_GRADIENT);g.setColors(new int[]{Color.argb(92,Color.red(color),Color.green(color),Color.blue(color)),Color.TRANSPARENT});g.setGradientRadius(dp(sizeDp)*.52f);o.setBackground(g);FrameLayout.LayoutParams p=new FrameLayout.LayoutParams(dp(sizeDp),dp(sizeDp),gravity);p.setMargins(-dp(80),-dp(65),-dp(80),dp(20));root.addView(o,p);ValueAnimator a=ValueAnimator.ofFloat(0,1);a.setDuration(duration);a.setRepeatCount(ValueAnimator.INFINITE);a.setRepeatMode(ValueAnimator.REVERSE);a.addUpdateListener(v->{float q=(float)v.getAnimatedValue();o.setTranslationX(dp(22)*q);o.setTranslationY(dp(28)*q);o.setScaleX(1+.08f*q);o.setScaleY(1+.08f*q);});a.start();}
    private GradientDrawable background(){return new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.rgb(5,8,15),Color.rgb(13,10,22),Color.rgb(6,12,18)});} private GradientDrawable liquid(int c,int r){int a=Color.alpha(c);int hi=Color.argb(Math.min(255,a+18),Math.min(255,Color.red(c)+32),Math.min(255,Color.green(c)+32),Math.min(255,Color.blue(c)+36));GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{hi,c,Color.argb(Math.max(24,a-28),Math.max(0,Color.red(c)-12),Math.max(0,Color.green(c)-12),Math.max(0,Color.blue(c)-8))});g.setCornerRadius(dp(r));g.setStroke(dp(1),Color.argb(68,255,255,255));return g;} private TextView label(String s,float sp,int style,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTypeface(Typeface.create("sans-serif",style));t.setTextColor(color);t.setIncludeFontPadding(false);return t;} private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
