package com.routix.app;
import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.net.Uri;import androidx.core.content.FileProvider;import org.json.*;import java.io.*;import java.net.*;import java.util.*;import java.util.zip.*;
/** In-app updater. Beta channel accepts only successful master builds from the official public repo. */
final class InAppUpdater{
 static final String OWNER="1337Detailing",REPO="RoutePilot",WORKFLOW="Build Routix APK";private final Activity a;
 interface Callback{void status(String text,int progress);void ready(Update u);void error(String message);}
 static final class Update{final long runId;final int runNumber;final long artifactId;final String sha;Update(long r,int n,long id,String s){runId=r;runNumber=n;artifactId=id;sha=s;}String version(){return "2.1."+runNumber+"-debug";}}
 InAppUpdater(Activity x){a=x;}
 void checkBeta(Callback cb){new Thread(()->{try{post(cb,"Recherche de la dernière bêta…",10);JSONObject root=json(get("https://api.github.com/repos/"+OWNER+"/"+REPO+"/actions/runs?branch=master&status=success&per_page=30"));JSONArray runs=root.getJSONArray("workflow_runs");JSONObject chosen=null;for(int i=0;i<runs.length();i++){JSONObject r=runs.getJSONObject(i);if(WORKFLOW.equals(r.optString("name"))&&"push".equals(r.optString("event"))&&"master".equals(r.optString("head_branch"))&&"success".equals(r.optString("conclusion"))){chosen=r;break;}}if(chosen==null)throw new IOException("Aucune build bêta réussie disponible");int rn=chosen.getInt("run_number");long installed=installedVersion();if(200000L+rn<=installed)throw new IOException("Tu as déjà la dernière bêta (build "+rn+").");post(cb,"Build #"+rn+" trouvée",35);JSONObject ar=json(get("https://api.github.com/repos/"+OWNER+"/"+REPO+"/actions/runs/"+chosen.getLong("id")+"/artifacts?name=Routix-debug"));JSONArray items=ar.getJSONArray("artifacts");if(items.length()==0)throw new IOException("L’APK de cette build n’est plus disponible");JSONObject art=items.getJSONObject(0);if(art.optBoolean("expired"))throw new IOException("L’artefact GitHub de cette build a expiré");Update u=new Update(chosen.getLong("id"),rn,art.getLong("id"),chosen.optString("head_sha"));a.runOnUiThread(()->cb.ready(u));}catch(Exception e){fail(cb,e);}},"routix-update-check").start();}
 void downloadAndInstall(Update u,Callback cb){new Thread(()->{File dir=new File(a.getCacheDir(),"updates");delete(dir);dir.mkdirs();File zip=new File(dir,"Routix-"+u.runNumber+".zip"),apk=new File(dir,"Routix-"+u.runNumber+".apk");try{post(cb,"Téléchargement de la bêta…",45);download("https://api.github.com/repos/"+OWNER+"/"+REPO+"/actions/artifacts/"+u.artifactId+"/zip",zip,cb);post(cb,"Préparation de l’APK…",88);unzipApk(zip,apk);if(apk.length()<500000)throw new IOException("APK téléchargé invalide");post(cb,"Ouverture de l’installateur…",100);a.runOnUiThread(()->install(apk));}catch(Exception e){fail(cb,e);}},"routix-update-download").start();}
 private long installedVersion(){try{return a.getPackageManager().getPackageInfo(a.getPackageName(),0).getLongVersionCode();}catch(Exception e){return 0;}}
 private void install(File apk){try{Uri uri=FileProvider.getUriForFile(a,a.getPackageName()+".files",apk);Intent i=new Intent(Intent.ACTION_VIEW).setDataAndType(uri,"application/vnd.android.package-archive").addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_ACTIVITY_NEW_TASK);a.startActivity(i);}catch(Exception e){new AlertDialog.Builder(a).setTitle("Installation impossible").setMessage("Autorise Routix à installer des applications inconnues dans les réglages Android, puis réessaie.\n\n"+e.getMessage()).setPositiveButton("OK",null).show();}}
 private static void unzipApk(File zip,File out)throws Exception{try(ZipInputStream z=new ZipInputStream(new FileInputStream(zip));FileOutputStream o=new FileOutputStream(out)){ZipEntry e;while((e=z.getNextEntry())!=null){if(!e.isDirectory()&&e.getName().toLowerCase(Locale.ROOT).endsWith(".apk")){byte[] b=new byte[32768];for(int n;(n=z.read(b))>0;)o.write(b,0,n);return;}}}throw new IOException("Aucun APK dans l’artefact GitHub");}
 private static void download(String url,File out,Callback cb)throws Exception{HttpURLConnection c=open(url);int redirects=0;while(c.getResponseCode()/100==3&&redirects++<6){String next=c.getHeaderField("Location");c.disconnect();if(next==null)throw new IOException("Redirection GitHub invalide");c=open(next);}if(c.getResponseCode()/100!=2)throw new IOException("GitHub refuse le téléchargement ("+c.getResponseCode()+")");long total=c.getContentLengthLong(),done=0;try(InputStream in=c.getInputStream();FileOutputStream o=new FileOutputStream(out)){byte[] b=new byte[32768];for(int n;(n=in.read(b))>0;){o.write(b,0,n);done+=n;if(total>0){int p=45+(int)Math.min(40,40d*done/total);post(cb,"Téléchargement… "+(100*done/total)+" %",p);}}}}
 private static HttpURLConnection open(String url)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setConnectTimeout(12000);c.setReadTimeout(45000);c.setInstanceFollowRedirects(false);c.setRequestProperty("Accept","application/vnd.github+json");c.setRequestProperty("X-GitHub-Api-Version","2022-11-28");c.setRequestProperty("User-Agent","Routix-Updater");return c;}
 private static String get(String url)throws Exception{HttpURLConnection c=open(url);if(c.getResponseCode()/100!=2)throw new IOException("GitHub indisponible ("+c.getResponseCode()+")");ByteArrayOutputStream o=new ByteArrayOutputStream();try(InputStream in=c.getInputStream()){byte[] b=new byte[16384];for(int n;(n=in.read(b))>0;)o.write(b,0,n);}return o.toString("UTF-8");}
 private static JSONObject json(String s)throws Exception{return new JSONObject(s);}private static void delete(File f){if(!f.exists())return;if(f.isDirectory()){File[]x=f.listFiles();if(x!=null)for(File q:x)delete(q);}f.delete();}
 private void post(Callback cb,String s,int p){a.runOnUiThread(()->cb.status(s,p));}private void fail(Callback cb,Exception e){DiagnosticLog.error("in-app updater",e);a.runOnUiThread(()->cb.error(e.getMessage()==null?"Mise à jour impossible":e.getMessage()));}
}