package com.routix.app;
import android.content.Context;import android.location.Location;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;

/** Small asynchronous OSM road window. Never blocks GPS; last good window remains usable offline. */
final class RoadContextProvider {
 interface Callback{void ready(List<RouteAwareAnalyzer.Road> roads);}
 private final Context context;private final ExecutorService io=Executors.newSingleThreadExecutor();private volatile List<RouteAwareAnalyzer.Road> roads=Collections.emptyList();private volatile double centerLat,centerLon;private volatile long lastRequest;private volatile boolean loading;
 RoadContextProvider(Context c){context=c.getApplicationContext();}
 List<RouteAwareAnalyzer.Road> nearby(Location l){if(l==null)return roads;float[] d=new float[1];Location.distanceBetween(l.getLatitude(),l.getLongitude(),centerLat,centerLon,d);if((roads.isEmpty()||d[0]>350)&&!loading&&System.currentTimeMillis()-lastRequest>15000)refresh(l,null);return roads;}
 void refresh(Location l,Callback cb){if(l==null||loading)return;loading=true;lastRequest=System.currentTimeMillis();double lat=l.getLatitude(),lon=l.getLongitude();io.execute(()->{List<RouteAwareAnalyzer.Road> r=loadCache(lat,lon);if(r.isEmpty())r=download(lat,lon);if(!r.isEmpty()){roads=Collections.unmodifiableList(r);centerLat=lat;centerLon=lon;}loading=false;if(cb!=null)cb.ready(roads);});}
 private List<RouteAwareAnalyzer.Road> download(double lat,double lon){String q="[out:json][timeout:12];way(around:650,"+lat+","+lon+")[highway][highway!~\"^(footway|cycleway|steps|path|bridleway|proposed|construction)$\"];out geom;";String[] endpoints={"https://overpass.kumi.systems/api/interpreter","https://overpass-api.de/api/interpreter"};for(String ep:endpoints){HttpURLConnection c=null;try{c=(HttpURLConnection)new URL(ep).openConnection();c.setRequestMethod("POST");c.setDoOutput(true);c.setConnectTimeout(4500);c.setReadTimeout(10000);c.setRequestProperty("User-Agent","Routix/2.1 road-context");try(OutputStream o=c.getOutputStream()){o.write(("data="+URLEncoder.encode(q,"UTF-8")).getBytes(StandardCharsets.UTF_8));}if(c.getResponseCode()!=200)continue;ByteArrayOutputStream b=new ByteArrayOutputStream();try(InputStream in=c.getInputStream()){byte[] x=new byte[8192];int n;while((n=in.read(x))>0){b.write(x,0,n);if(b.size()>6*1024*1024)throw new IOException();}}String json=b.toString("UTF-8");List<RouteAwareAnalyzer.Road> r=parse(json);if(!r.isEmpty()){saveCache(lat,lon,json);return r;}}catch(Exception ignored){}finally{if(c!=null)c.disconnect();}}return Collections.emptyList();}
 private List<RouteAwareAnalyzer.Road> parse(String json)throws Exception{JSONArray es=new JSONObject(json).optJSONArray("elements");List<RouteAwareAnalyzer.Road> out=new ArrayList<>();if(es==null)return out;for(int i=0;i<es.length();i++){JSONObject e=es.getJSONObject(i),tags=e.optJSONObject("tags");JSONArray g=e.optJSONArray("geometry");if(g==null||g.length()<2)continue;String name=tags==null?"":tags.optString("name",tags.optString("ref",""));for(int j=1;j<g.length();j++){JSONObject a=g.getJSONObject(j-1),b=g.getJSONObject(j);out.add(new RouteAwareAnalyzer.Road(e.optString("id")+":"+j,name,a.getDouble("lat"),a.getDouble("lon"),b.getDouble("lat"),b.getDouble("lon")));}}return out;}
 private File cache(double lat,double lon){File d=new File(context.getFilesDir(),"road_context");d.mkdirs();return new File(d,Math.round(lat*100)+"_"+Math.round(lon*100)+".json");}
 private List<RouteAwareAnalyzer.Road> loadCache(double lat,double lon){try{File f=cache(lat,lon);if(!f.exists())return Collections.emptyList();return parse(new String(java.nio.file.Files.readAllBytes(f.toPath()),StandardCharsets.UTF_8));}catch(Exception e){return Collections.emptyList();}}
 private void saveCache(double lat,double lon,String json){try{RouteArchive.atomic(cache(lat,lon),json.getBytes(StandardCharsets.UTF_8));}catch(Exception ignored){}}
 void close(){io.shutdownNow();}
}
