package com.routix.app;

import android.Manifest;
import android.app.AlertDialog;
import android.content.Intent;
import android.content.SharedPreferences;
import android.content.pm.PackageManager;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Typeface;
import android.graphics.drawable.ColorDrawable;
import android.graphics.drawable.GradientDrawable;
import android.location.Location;
import android.net.Uri;
import android.os.Bundle;
import android.text.Editable;
import android.text.InputType;
import android.text.TextWatcher;
import android.view.Gravity;
import android.view.HapticFeedbackConstants;
import android.view.MotionEvent;
import android.view.View;
import android.view.ViewGroup;
import android.view.Window;
import android.view.WindowManager;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.ActivityCompat;
import androidx.core.content.ContextCompat;
import androidx.core.content.FileProvider;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowCompat;
import androidx.core.view.WindowInsetsCompat;

import org.json.JSONArray;
import org.json.JSONObject;
import org.osmdroid.config.Configuration;
import org.osmdroid.util.GeoPoint;
import org.osmdroid.views.MapView;
import org.osmdroid.views.overlay.Polyline;

import java.io.BufferedReader;
import java.io.File;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Locale;

/** Routix 2.1 — terrain-first navigation with an Apple-like liquid interface. */
public class RoutixActivity extends AppCompatActivity {
    private static final int LOCATION_PERMISSION=42, NOTIFICATION_PERMISSION=43, IMPORT_GPX=1337;
    private static final int BG=Color.rgb(12,13,20), SURFACE=Color.rgb(30,30,46), SURFACE2=Color.rgb(49,50,68);
    private static final int TEXT=Color.rgb(240,242,255), MUTED=Color.rgb(166,173,200), GREEN=Color.rgb(166,227,161), PEACH=Color.rgb(250,179,135), RED=Color.rgb(243,139,168), MAUVE=Color.rgb(203,166,247), BLUE=Color.rgb(137,180,250), PINK=Color.rgb(244,184,228), TEAL=Color.rgb(148,226,213), YELLOW=Color.rgb(249,226,175);

    private SharedPreferences prefs; private RouteStore store; private WorkHoursStore hoursStore; private Location lastLocation;
    private ModernMapController modern; private TrackingService tracker; private boolean bound,visible,headingUp=true,offline; private Bundle mapState; private boolean recoveryOffered;
    private FrameLayout root; private MapView map; private View topBar,dock,recordSheet; private LinearLayout contentHost; private CompactSpeedometer headerSpeed; private ImageView mapLogo;
    private Polyline remainingLine; private RouteArrowsOverlay routeArrows; private int systemTop,systemBottom; private String selectedTab="map"; private int accent=MAUVE;
    private boolean recording,paused,guiding,guidanceCameraFollow=true; private long recordingStarted,guidanceSession; private double recordedDistance;
    private TextView recordMain,recordStatus,recordDistance,recordPoints,recordEvents,reverseButton,twoSidesButton,pauseButton,guideTitle,guideSubtitle,guideDistance,guideProgress;
    private GuidanceEngine guidance; private RouteStore.Summary guidingRoute;

    @Override protected void onCreate(Bundle state){
        super.onCreate(state);mapState=state;WindowCompat.setDecorFitsSystemWindows(getWindow(),false);getWindow().setStatusBarColor(Color.TRANSPARENT);getWindow().setNavigationBarColor(BG);
        prefs=getSharedPreferences("routix",MODE_PRIVATE);migrateMapPreference();accent=prefs.getInt("accent_color",MAUVE);store=new RouteStore(this,prefs);hoursStore=new WorkHoursStore(prefs);
        Configuration.getInstance().setCacheMapTileCount((short)64);Configuration.getInstance().setTileFileSystemCacheMaxBytes(64L*1024*1024);Configuration.getInstance().setTileFileSystemCacheTrimBytes(48L*1024*1024);Configuration.getInstance().setUserAgentValue(getPackageName()+"/2.1 Routix");Configuration.getInstance().setOsmdroidBasePath(new File(getCacheDir(),"osmdroid"));Configuration.getInstance().setOsmdroidTileCache(new File(getCacheDir(),"osmdroid/tiles"));
        root=new FrameLayout(this);root.setBackgroundColor(BG);buildMap();topBar=buildTopBar();contentHost=new LinearLayout(this);contentHost.setOrientation(LinearLayout.VERTICAL);dock=buildDock();root.addView(topBar);root.addView(contentHost);root.addView(dock);setContentView(root);
        ViewCompat.setOnApplyWindowInsetsListener(root,(v,in)->{androidx.core.graphics.Insets b=in.getInsets(WindowInsetsCompat.Type.systemBars()|WindowInsetsCompat.Type.displayCutout());systemTop=b.top;systemBottom=b.bottom;positionChrome();return in;});ViewCompat.requestApplyInsets(root);
        showTab("map",false);ensureLocation();applyRuntimePrefs();new Thread(()->{store.restoreBackups();runOnUiThread(()->{if(!isDestroyed()&&"routes".equals(selectedTab))showTab("routes",false);});},"restore-backups").start();
    }

    private void migrateMapPreference(){String s=prefs==null?null:prefs.getString("map_style",null);if(s==null||s.startsWith("apple_")||"terrain".equals(s))prefs.edit().putString("map_style","osm").apply();}

    private void buildMap(){
        map=new MapView(this);map.setUseDataConnection(false);map.setMultiTouchControls(true);map.setMinZoomLevel(3.0);map.setMaxZoomLevel(20.0);map.getController().setZoom(18.0);map.setHorizontalMapRepetitionEnabled(false);map.setVerticalMapRepetitionEnabled(false);map.setOnTouchListener((v,e)->{if(e.getActionMasked()==MotionEvent.ACTION_DOWN&&guiding)guidanceCameraFollow=false;return false;});applyMapStyle();root.addView(map,new FrameLayout.LayoutParams(-1,-1));

        remainingLine=new Polyline();remainingLine.getOutlinePaint().setStrokeCap(Paint.Cap.ROUND);remainingLine.getOutlinePaint().setStrokeJoin(Paint.Join.ROUND);map.getOverlays().add(remainingLine);routeArrows=new RouteArrowsOverlay();map.getOverlays().add(routeArrows);
        mapLogo=new ImageView(this);mapLogo.setImageResource(R.drawable.routix_logo_v2);mapLogo.setScaleType(ImageView.ScaleType.CENTER_CROP);mapLogo.setPadding(dp(4),dp(4),dp(4),dp(4));mapLogo.setBackground(glass(SURFACE,18));mapLogo.setElevation(dp(10));root.addView(mapLogo,new FrameLayout.LayoutParams(dp(52),dp(52)));
    }

    private void applyMapStyle(){
        if(map==null)return;map.setUseDataConnection(false);offline=false;
        FranceOfflineManager.Pack pack=FranceOfflineManager.find(prefs.getString("offline_pack",""));
        if(pack!=null&&FranceOfflineManager.isInstalled(this,pack))try{
            org.mapsforge.map.android.graphics.AndroidGraphicFactory.createInstance(getApplication());
            String name=MapStyles.dark(prefs)?"dark":"light";File theme=new File(getCacheDir(),"offline-"+name+".xml");
            try(java.io.InputStream in=getAssets().open("maps/"+name+".xml")){java.nio.file.Files.copy(in,theme.toPath(),java.nio.file.StandardCopyOption.REPLACE_EXISTING);}
            org.osmdroid.mapsforge.MapsForgeTileSource source=org.osmdroid.mapsforge.MapsForgeTileSource.createFromFiles(new File[]{FranceOfflineManager.file(this,pack)},new org.mapsforge.map.rendertheme.ExternalRenderTheme(theme),"routix-"+name,"fr");
            map.setTileProvider(new org.osmdroid.mapsforge.MapsForgeTileProvider(new org.osmdroid.tileprovider.util.SimpleRegisterReceiver(this),source,null));offline=true;
        }catch(Exception e){DiagnosticLog.error("offline map",e);toast("Pack hors ligne illisible : carte en ligne utilisée");}
        if(modern!=null){modern.refreshStyle();modern.setVisible(!offline&&"map".equals(selectedTab));}
        map.setVisibility(offline&&"map".equals(selectedTab)?View.VISIBLE:View.GONE);map.setAlpha(offline?1:0);if(guiding)redrawGuidance();map.invalidate();
    }

    private Bitmap createPositionIcon(String style){
        int z=dp(prefs==null?54:prefs.getInt("position_icon_size",54));Bitmap b=Bitmap.createBitmap(z,z,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(b);Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);p.setShadowLayer(dp(5),0,dp(2),Color.argb(145,0,0,0));p.setColor(Color.argb(226,Color.red(accent),Color.green(accent),Color.blue(accent)));c.drawCircle(z/2f,z/2f,z*.43f,p);p.clearShadowLayer();p.setColor(Color.WHITE);
        if("Bonhomme".equals(style)){c.drawCircle(z*.5f,z*.31f,z*.09f,p);c.drawRoundRect(z*.43f,z*.40f,z*.57f,z*.67f,dp(4),dp(4),p);p.setStrokeWidth(dp(4));p.setStrokeCap(Paint.Cap.ROUND);c.drawLine(z*.45f,z*.51f,z*.34f,z*.61f,p);c.drawLine(z*.55f,z*.51f,z*.66f,z*.61f,p);c.drawLine(z*.47f,z*.65f,z*.40f,z*.78f,p);c.drawLine(z*.53f,z*.65f,z*.60f,z*.78f,p);}
        else if("Voiture".equals(style)){c.drawRoundRect(z*.31f,z*.20f,z*.69f,z*.80f,dp(7),dp(7),p);p.setColor(Color.argb(210,25,32,44));c.drawRoundRect(z*.36f,z*.31f,z*.64f,z*.49f,dp(4),dp(4),p);p.setColor(Color.WHITE);c.drawRect(z*.27f,z*.30f,z*.32f,z*.45f,p);c.drawRect(z*.68f,z*.30f,z*.73f,z*.45f,p);c.drawRect(z*.27f,z*.58f,z*.32f,z*.73f,p);c.drawRect(z*.68f,z*.58f,z*.73f,z*.73f,p);}
        else if("Flèche".equals(style)){android.graphics.Path path=new android.graphics.Path();path.moveTo(z*.5f,z*.18f);path.lineTo(z*.72f,z*.76f);path.lineTo(z*.5f,z*.64f);path.lineTo(z*.28f,z*.76f);path.close();c.drawPath(path,p);}
        else if("Point".equals(style)){c.drawCircle(z*.5f,z*.5f,z*.18f,p);}
        else {c.drawRoundRect(z*.29f,z*.17f,z*.71f,z*.78f,dp(7),dp(7),p);p.setColor(Color.argb(210,25,32,44));c.drawRoundRect(z*.34f,z*.22f,z*.66f,z*.38f,dp(3),dp(3),p);p.setColor(Color.argb(235,210,235,245));c.drawRoundRect(z*.34f,z*.44f,z*.66f,z*.69f,dp(4),dp(4),p);p.setColor(Color.WHITE);c.drawRect(z*.25f,z*.26f,z*.31f,z*.43f,p);c.drawRect(z*.69f,z*.26f,z*.75f,z*.43f,p);c.drawRect(z*.25f,z*.57f,z*.31f,z*.74f,p);c.drawRect(z*.69f,z*.57f,z*.75f,z*.74f,p);}
        p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(2));p.setColor(Color.argb(225,255,255,255));c.drawCircle(z/2f,z/2f,z*.43f,p);return b;
    }

    private View buildTopBar(){
        LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(12),dp(6),dp(8),dp(6));bar.setBackground(glass(SURFACE,24));bar.setElevation(dp(10));
        headerSpeed=new CompactSpeedometer(this);bar.addView(headerSpeed,new LinearLayout.LayoutParams(dp(80),dp(50)));
        TextView status=text("COLLECTE\nGPS terrain",11,Typeface.BOLD,MUTED);bar.addView(status,new LinearLayout.LayoutParams(0,-2,1));
        TextView north=icon(headingUp?"↑":"N");north.setContentDescription("Basculer cap en haut ou nord en haut");north.setOnClickListener(v->{headingUp=!headingUp;north.setText(headingUp?"↑":"N");if(modern!=null)modern.heading(headingUp);if(!headingUp)map.setMapOrientation(0);recenter();});bar.addView(north,new LinearLayout.LayoutParams(dp(48),dp(48)));
        TextView loc=icon("◎");loc.setContentDescription("Recentrer la carte");loc.setOnClickListener(v->{guidanceCameraFollow=true;recenter();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(48),dp(48));lp.leftMargin=dp(6);bar.addView(loc,lp);return bar;
    }
    private View buildDock(){LinearLayout row=new LinearLayout(this);row.setPadding(dp(4),dp(4),dp(4),dp(4));row.setBackground(glass(SURFACE,24));row.setElevation(dp(12));tab(row,"⌖","Carte","map");tab(row,"●","Enregistrer","record");tab(row,"≡","Tournées","routes");tab(row,"•••","Plus","more");return row;}
    private void tab(LinearLayout row,String glyph,String label,String key){TextView t=text(label,11,Typeface.BOLD,MUTED);TerrainIcon symbol=new TerrainIcon(key,MUTED);symbol.setBounds(0,0,dp(22),dp(22));t.setCompoundDrawables(null,symbol,null,null);t.setCompoundDrawablePadding(dp(4));t.setGravity(Gravity.CENTER);t.setTag(key);t.setContentDescription(label);t.setOnClickListener(v->showTab(key,true));row.addView(t,new LinearLayout.LayoutParams(0,-1,1));}

    private void showTab(String key,boolean animate){
        selectedTab=key;contentHost.animate().cancel();contentHost.setAlpha(1);contentHost.setTranslationY(0);contentHost.setScaleX(1);contentHost.setScaleY(1);contentHost.removeAllViews();boolean mapMode="map".equals(key);map.setVisibility(mapMode&&offline?View.VISIBLE:View.GONE);if(modern!=null)modern.setVisible(mapMode&&!offline);topBar.setVisibility(View.VISIBLE);if(mapLogo!=null)mapLogo.setVisibility(mapMode&&false?View.VISIBLE:View.GONE);
        if(mapMode)contentHost.addView(mapCard());else if("record".equals(key))contentHost.addView(recordPage());else if("routes".equals(key))contentHost.addView(routesPage());else if("hours".equals(key))contentHost.addView(hoursPage());else if("gpxlab".equals(key))contentHost.addView(gpxLabPage());else if("settings".equals(key))contentHost.addView(settingsPage());else if("more".equals(key))contentHost.addView(morePage());recordSheet="record".equals(key)?contentHost:null;updateDock();positionChrome();
        if(mapMode&&guiding&&tracker!=null)updateRouteGuidance(lastLocation);if(animate&&prefs.getBoolean("animations",true)){int d=animDuration();contentHost.setAlpha(0);contentHost.setTranslationY(dp(prefs.getBoolean("rich_animations",true)?20:8));contentHost.setScaleX(prefs.getBoolean("rich_animations",true)?.982f:1f);contentHost.setScaleY(prefs.getBoolean("rich_animations",true)?.982f:1f);contentHost.animate().alpha(1).translationY(0).scaleX(1).scaleY(1).setDuration(d).start();}
    }
    private void updateDock(){ViewGroup r=(ViewGroup)dock;for(int i=0;i<r.getChildCount();i++){TextView t=(TextView)r.getChildAt(i);boolean on=selectedTab.equals(t.getTag())||("more".equals(t.getTag())&&!"map".equals(selectedTab)&&!"record".equals(selectedTab)&&!"routes".equals(selectedTab));t.setTextColor(on?accent:MUTED);TerrainIcon symbol=new TerrainIcon(String.valueOf(t.getTag()),on?accent:MUTED);symbol.setBounds(0,0,dp(22),dp(22));t.setCompoundDrawables(null,symbol,null,null);t.setBackground(on?glass(SURFACE2,21):null);if(prefs.getBoolean("rich_animations",true))t.animate().scaleX(on?1.055f:1f).scaleY(on?1.055f:1f).setDuration(180).start();}}

    private View mapCard(){
        LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(15),dp(13),dp(15),dp(13));card.setBackground(glass(SURFACE,28));card.setElevation(dp(12));
        LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);guideTitle=text(guiding?"Suis les flèches":"Carte",19,Typeface.BOLD,TEXT);guideSubtitle=text(guiding?"Le tracé se nettoie derrière toi en temps réel":"Choisis une tournée ou enregistre ton parcours",11,Typeface.NORMAL,MUTED);titles.addView(guideTitle);titles.addView(guideSubtitle);head.addView(titles,new LinearLayout.LayoutParams(0,-2,1));
        if(guiding){reverseButton=flagBubble("↶",PEACH);twoSidesButton=flagBubble("⇆",GREEN);reverseButton.setContentDescription("Ajouter marche arrière");twoSidesButton.setContentDescription("Ajouter 2 côtés");reverseButton.setOnClickListener(v->addGuidanceFlag("REVERSE","Marche arrière"));twoSidesButton.setOnClickListener(v->addGuidanceFlag("TWO_SIDES","2 côtés"));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(dp(46),dp(46));bp.leftMargin=dp(6);head.addView(reverseButton,bp);LinearLayout.LayoutParams bp2=new LinearLayout.LayoutParams(dp(46),dp(46));bp2.leftMargin=dp(6);head.addView(twoSidesButton,bp2);}
        card.addView(head);LinearLayout row=new LinearLayout(this);row.setPadding(0,dp(10),0,0);guideDistance=metric("—","RESTANT");guideProgress=metric("—","PROGRESSION");guideDistance.setVisibility(prefs.getBoolean("show_remaining",true)?View.VISIBLE:View.GONE);guideProgress.setVisibility(prefs.getBoolean("show_progress",true)?View.VISIBLE:View.GONE);row.addView(guideDistance,new LinearLayout.LayoutParams(0,dp(62),1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(62),1);p.leftMargin=dp(8);row.addView(guideProgress,p);card.addView(row);
        if(guiding){LinearLayout controls=new LinearLayout(this);controls.setPadding(0,dp(9),0,0);TextView follow=pill("◎ Me suivre",SURFACE2);follow.setOnClickListener(v->{press(v);guidanceCameraFollow=true;recenter();});TextView resume=pill("Reprendre ici",SURFACE2);resume.setOnClickListener(v->resumeGuidanceHere());TextView stop=pill("Arrêter",Color.argb(160,Color.red(RED),Color.green(RED),Color.blue(RED)));stop.setOnClickListener(v->stopGuidance());controls.addView(follow,new LinearLayout.LayoutParams(0,dp(44),1));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(0,dp(44),1);rp.leftMargin=dp(6);controls.addView(resume,rp);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(0,dp(44),.8f);sp.leftMargin=dp(6);controls.addView(stop,sp);card.addView(controls);}
        return card;
    }
    private TextView flagBubble(String glyph,int color){TextView t=text(glyph,22,Typeface.BOLD,color);t.setGravity(Gravity.CENTER);t.setBackground(glass(SURFACE2,23));t.setElevation(dp(4));return t;}

    private View recordPage(){
        ScrollView sv=new ScrollView(this);LinearLayout p=page("Enregistrer","GPS terrain, repères rapides et sauvegarde automatique.");recordStatus=text(recording?(paused?"EN PAUSE":"ENREGISTREMENT ACTIF"):"PRÊT",13,Typeface.BOLD,recording?GREEN:MUTED);p.addView(recordStatus);LinearLayout stats=new LinearLayout(this);stats.setPadding(0,dp(12),0,dp(12));recordDistance=metric(formatDistance(recordedDistance),"DISTANCE");recordPoints=metric(String.valueOf(tracker==null?0:tracker.points.size()),"POINTS");recordEvents=metric(String.valueOf(tracker==null?0:tracker.events.size()),"REPÈRES");stats.addView(recordDistance,new LinearLayout.LayoutParams(0,dp(68),1));stats.addView(recordPoints,new LinearLayout.LayoutParams(0,dp(68),1));stats.addView(recordEvents,new LinearLayout.LayoutParams(0,dp(68),1));p.addView(stats);
        LinearLayout main=new LinearLayout(this);recordMain=pill(recording?"Terminer et sauvegarder":"Commencer l’enregistrement",recording?RED:accent);recordMain.setOnClickListener(v->{press(v);if(recording)finishRecording();else startRecording();});main.addView(recordMain,new LinearLayout.LayoutParams(0,dp(58),1));reverseButton=flagBubble("↶",PEACH);twoSidesButton=flagBubble("⇆",GREEN);reverseButton.setOnClickListener(v->addEvent("REVERSE","Marche arrière"));twoSidesButton.setOnClickListener(v->addEvent("TWO_SIDES","2 côtés"));LinearLayout.LayoutParams b1=new LinearLayout.LayoutParams(dp(54),dp(54));b1.leftMargin=dp(8);main.addView(reverseButton,b1);LinearLayout.LayoutParams b2=new LinearLayout.LayoutParams(dp(54),dp(54));b2.leftMargin=dp(7);main.addView(twoSidesButton,b2);p.addView(main);
        pauseButton=pill(paused?"Reprendre":"Pause",SURFACE2);pauseButton.setOnClickListener(v->togglePause());LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(46));pp.topMargin=dp(8);p.addView(pauseButton,pp);setFlagEnabled(recording);TextView info=text("↶ marche arrière  •  ⇆ 2 côtés\nPoints sauvegardés en continu • brouillon toutes les 15 s • filtre précision "+prefs.getInt("record_accuracy",45)+" m",12,Typeface.NORMAL,MUTED);info.setPadding(0,dp(17),0,0);p.addView(info);sv.addView(p);return sv;
    }

    private View routesPage(){
        ScrollView sv=new ScrollView(this);LinearLayout p=page("Tournées",store.routeFiles().size()+" tournée(s) • tes parcours et repères");LinearLayout actions=new LinearLayout(this);TextView imp=pill("Importer GPX",accent);imp.setOnClickListener(v->importGpx());TextView rec=pill("Nouvelle tournée",SURFACE2);rec.setOnClickListener(v->showTab("record",true));actions.addView(imp,new LinearLayout.LayoutParams(0,dp(50),1));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(0,dp(50),1);rp.leftMargin=dp(8);actions.addView(rec,rp);p.addView(actions);
        EditText search=new EditText(this);search.setHint("Rechercher une tournée");search.setHintTextColor(Color.argb(120,255,255,255));search.setTextColor(TEXT);search.setTextSize(14);search.setSingleLine(true);search.setPadding(dp(15),0,dp(15),0);search.setBackground(glass(SURFACE,18));LinearLayout.LayoutParams sl=new LinearLayout.LayoutParams(-1,dp(48));sl.topMargin=dp(12);p.addView(search,sl);
        LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams ll=new LinearLayout.LayoutParams(-1,-2);ll.topMargin=dp(4);p.addView(list,ll);List<File> files=store.routeFiles();renderRoutes(list,files,"");search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){renderRoutes(list,files,s.toString());}public void afterTextChanged(Editable e){}});sv.addView(p);return sv;
    }
    private void renderRoutes(LinearLayout list,List<File> files,String query){list.removeAllViews();String q=query==null?"":query.trim().toLowerCase(Locale.ROOT);int shown=0;for(File f:files){if(!q.isEmpty()&&!store.displayName(f).toLowerCase(Locale.ROOT).contains(q))continue;list.addView(routeCard(f,shown++));}if(shown==0){TextView e=infoCard(query==null||query.trim().isEmpty()?"Aucune tournée":"Aucun résultat",query==null||query.trim().isEmpty()?"Importe un GPX ou enregistre ton premier parcours.":"Essaie un autre nom de tournée.");LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(14);list.addView(e,lp);}}
    private View routeCard(File f,int index){
        RouteStore.Summary s=store.parse(f);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(15),dp(14),dp(15),dp(14));c.setBackground(glass(SURFACE,23));c.setElevation(dp(5));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.topMargin=dp(10);c.setLayoutParams(cp);
        LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView fav=text(store.isFavorite(f)?"★":"☆",21,Typeface.BOLD,store.isFavorite(f)?YELLOW:MUTED);fav.setGravity(Gravity.CENTER);fav.setOnClickListener(v->{press(v);store.setFavorite(f,!store.isFavorite(f));showTab("routes",false);});head.addView(fav,new LinearLayout.LayoutParams(dp(40),dp(40)));LinearLayout names=new LinearLayout(this);names.setOrientation(LinearLayout.VERTICAL);names.addView(text(store.displayName(f),17,Typeface.BOLD,TEXT));String source=f.getName().startsWith("Import_")?"IMPORT GPX":"TERRAIN ROUTIX";int confidence=prefs.getInt("import_confidence_"+f.getName(),100);names.addView(text(formatDate(f.lastModified())+" • "+source+(f.getName().startsWith("Import_")?" • "+confidence+" % confiance":""),10,Typeface.NORMAL,MUTED));head.addView(names,new LinearLayout.LayoutParams(0,-2,1));TextView more=icon("•••");more.setOnClickListener(v->routeMenu(f,s));head.addView(more,new LinearLayout.LayoutParams(dp(44),dp(42)));c.addView(head);
        LinearLayout stats=new LinearLayout(this);stats.setPadding(0,dp(12),0,dp(12));stats.addView(summaryStat("DISTANCE",formatDistance(s.distanceM)),new LinearLayout.LayoutParams(0,-2,1));stats.addView(summaryStat("DURÉE",formatDuration(s.durationMs)),new LinearLayout.LayoutParams(0,-2,1));stats.addView(summaryStat("POINTS",String.valueOf(s.points.size())),new LinearLayout.LayoutParams(0,-2,1));stats.addView(summaryStat("REPÈRES",String.valueOf(s.events.size())),new LinearLayout.LayoutParams(0,-2,1));c.addView(stats);
        LinearLayout a=new LinearLayout(this);TextView guide=pill("▶ Démarrer",accent);guide.setOnClickListener(v->startGuidance(s));TextView plan=pill("Plan",SURFACE2);plan.setOnClickListener(v->PrintablePlan.open(this,s,store.displayName(f)));TextView lab=pill("Aller au départ",SURFACE2);lab.setOnClickListener(v->{if(!s.points.isEmpty())DepartureNavigation.open(this,lastLocation,s.points.get(0));});a.addView(guide,new LinearLayout.LayoutParams(0,dp(45),1.25f));LinearLayout.LayoutParams p1=new LinearLayout.LayoutParams(0,dp(45),.8f);p1.leftMargin=dp(6);a.addView(plan,p1);LinearLayout.LayoutParams p2=new LinearLayout.LayoutParams(0,dp(45),.9f);p2.leftMargin=dp(6);a.addView(lab,p2);c.addView(a);c.setOnClickListener(v->{press(v);PrintablePlan.open(this,s,store.displayName(f));});
        if(prefs.getBoolean("animations",true)){c.setAlpha(0);c.setTranslationY(dp(14));c.animate().alpha(1).translationY(0).setDuration(animDuration()).setStartDelay(Math.min(240,index*45L)).start();}return c;
    }
    private void routeMenu(File f,RouteStore.Summary s){String[] x={store.isFavorite(f)?"☆ Retirer des favoris":"★ Ajouter aux favoris","✎ Renommer","⧉ Dupliquer","↗ Partager le GPX","▣ Générer le plan","Avancé : GPX Lab","⌫ Supprimer"};new AlertDialog.Builder(this).setTitle(store.displayName(f)).setMessage(formatDistance(s.distanceM)+" • "+formatDuration(s.durationMs)+" • "+s.points.size()+" points").setItems(x,(d,w)->{if(w==0){store.setFavorite(f,!store.isFavorite(f));showTab("routes",false);}else if(w==1)rename(f);else if(w==2){store.duplicate(f);showTab("routes",false);}else if(w==3)share(f);else if(w==4)PrintablePlan.open(this,s,store.displayName(f));else if(w==5){prefs.edit().putString("gpx_lab_file",f.getName()).apply();showTab("gpxlab",true);}else new AlertDialog.Builder(this).setTitle("Supprimer ?").setMessage("La copie durable dans Téléchargements/Routix reste conservée.").setNegativeButton("Annuler",null).setPositiveButton("Supprimer",(a,b)->{store.delete(f);showTab("routes",false);}).show();}).show();}
    private void rename(File f){EditText e=new EditText(this);e.setText(store.displayName(f));e.setSingleLine(true);new AlertDialog.Builder(this).setTitle("Nom de la tournée").setView(e).setNegativeButton("Annuler",null).setPositiveButton("Enregistrer",(d,w)->{store.rename(f,e.getText().toString());showTab("routes",false);}).show();}
    private void share(File f){try{Uri u=FileProvider.getUriForFile(this,getPackageName()+".files",f);Intent i=new Intent(Intent.ACTION_SEND);i.setType("application/gpx+xml");i.putExtra(Intent.EXTRA_STREAM,u);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Partager la tournée"));}catch(Exception e){toast("Partage impossible");}}

    private View hoursPage(){
        ScrollView sv=new ScrollView(this);LinearLayout p=page("Heures","Suivi local • calcul mensuel automatique");String month=new SimpleDateFormat("yyyy-MM",Locale.FRANCE).format(new Date());List<WorkHoursStore.Entry> entries=hoursStore.entries();int total=hoursStore.totalForMonth(month),days=0;for(WorkHoursStore.Entry e:entries)if(month.equals(e.monthKey()))days++;
        LinearLayout summary=new LinearLayout(this);summary.setOrientation(LinearLayout.VERTICAL);summary.setPadding(dp(18),dp(16),dp(18),dp(16));summary.setBackground(glass(Color.rgb(28,52,84),26));summary.setElevation(dp(7));summary.addView(text(monthLabel(month).toUpperCase(Locale.FRANCE),10,Typeface.BOLD,BLUE));summary.addView(text(formatMinutes(total),32,Typeface.BOLD,TEXT));summary.addView(text(days+" jour(s) • moyenne "+(days==0?"0h00":formatMinutes(total/days))+" / jour",11,Typeface.NORMAL,MUTED));p.addView(summary);
        TextView add=pill("＋ Ajouter une journée",accent);add.setOnClickListener(v->showHoursEntrySheet());LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(50));ap.topMargin=dp(11);ap.bottomMargin=dp(10);p.addView(add,ap);
        for(WorkHoursStore.Entry e:entries){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(14),dp(12),dp(14),dp(12));card.setBackground(glass(SURFACE,20));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);LinearLayout date=new LinearLayout(this);date.setOrientation(LinearLayout.VERTICAL);date.addView(text(dayLabel(e.date),15,Typeface.BOLD,TEXT));date.addView(text(e.date,10,Typeface.NORMAL,MUTED));top.addView(date,new LinearLayout.LayoutParams(0,-2,1));TextView net=pill(formatMinutes(e.netMinutes()),Color.argb(150,Color.red(BLUE),Color.green(BLUE),Color.blue(BLUE)));top.addView(net,new LinearLayout.LayoutParams(dp(86),dp(36)));card.addView(top);LinearLayout st=new LinearLayout(this);st.setPadding(0,dp(10),0,0);st.addView(summaryStat("DÉBUT",timeLabel(e.startMinutes)),new LinearLayout.LayoutParams(0,-2,1));st.addView(summaryStat("FIN",timeLabel(e.endMinutes)),new LinearLayout.LayoutParams(0,-2,1));st.addView(summaryStat("PAUSE",e.pauseMinutes+" min"),new LinearLayout.LayoutParams(0,-2,1));card.addView(st);TextView del=text("Supprimer",11,Typeface.BOLD,RED);del.setGravity(Gravity.END);del.setPadding(0,dp(8),0,0);del.setOnClickListener(v->{hoursStore.delete(e.id);showTab("hours",false);});card.addView(del);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(8);p.addView(card,lp);}sv.addView(p);return sv;
    }
    private void showHoursEntrySheet(){
        LinearLayout panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(dp(18),dp(18),dp(18),dp(16));panel.setBackground(glass(SURFACE,28));String date=todayKey();panel.addView(text("Ajouter des heures",24,Typeface.BOLD,TEXT));TextView sub=text(dayLabel(date)+" • "+date,11,Typeface.NORMAL,MUTED);sub.setPadding(0,dp(3),0,dp(13));panel.addView(sub);
        EditText start=hoursInput("Début • ex. 730",prefs.getString("hours_last_start",""));EditText end=hoursInput("Fin • ex. 1530",prefs.getString("hours_last_end",""));EditText pause=hoursInput("Pause • minutes",String.valueOf(prefs.getInt("hours_last_pause",30)));panel.addView(start,new LinearLayout.LayoutParams(-1,dp(52)));LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(-1,dp(52));ep.topMargin=dp(8);panel.addView(end,ep);
        LinearLayout now=new LinearLayout(this);TextView startNow=pill("Début = maintenant",SURFACE2);TextView endNow=pill("Fin = maintenant",SURFACE2);startNow.setOnClickListener(v->start.setText(timeLabel(nowMinutes())));endNow.setOnClickListener(v->end.setText(timeLabel(nowMinutes())));now.addView(startNow,new LinearLayout.LayoutParams(0,dp(38),1));LinearLayout.LayoutParams n2=new LinearLayout.LayoutParams(0,dp(38),1);n2.leftMargin=dp(6);now.addView(endNow,n2);LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(-1,-2);np.topMargin=dp(8);panel.addView(now,np);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(52));pp.topMargin=dp(9);panel.addView(pause,pp);
        TextView hint=text("730, 0730 ou 7:30 deviennent automatiquement 07:30.",10,Typeface.NORMAL,MUTED);LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(-1,-2);hp.topMargin=dp(8);hp.bottomMargin=dp(8);panel.addView(hint,hp);LinearLayout quick=new LinearLayout(this);for(int m:new int[]{0,20,30,45,60}){TextView q=pill(m+" min",SURFACE2);q.setTextSize(10);q.setOnClickListener(v->pause.setText(String.valueOf(m)));quick.addView(q,new LinearLayout.LayoutParams(0,dp(36),1));}panel.addView(quick);
        AlertDialog d=new AlertDialog.Builder(this).setView(panel).setNegativeButton("Annuler",null).setPositiveButton("Enregistrer",null).create();d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{int a=parseClock(start.getText().toString()),b=parseClock(end.getText().toString()),br=parsePositive(pause.getText().toString());if(a<0||b<0){toast("Heure invalide • exemple : 730 ou 1530");return;}int gross=b>=a?b-a:b+1440-a;if(br>=gross){toast("La pause doit être plus courte que le service");return;}hoursStore.add(date,a,b,br);prefs.edit().putString("hours_last_start",timeLabel(a)).putString("hours_last_end",timeLabel(b)).putInt("hours_last_pause",br).apply();d.dismiss();showTab("hours",true);}));d.show();Window w=d.getWindow();if(w!=null){w.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));w.setDimAmount(.45f);w.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);} }
    private EditText hoursInput(String hint,String value){EditText e=new EditText(this);e.setSingleLine(true);e.setHint(hint);e.setHintTextColor(Color.argb(120,255,255,255));e.setTextColor(TEXT);e.setTextSize(15);e.setInputType(InputType.TYPE_CLASS_NUMBER);e.setPadding(dp(15),0,dp(15),0);e.setBackground(glass(SURFACE2,18));if(value!=null)e.setText(value);return e;}

    private View gpxLabPage(){
        ScrollView sv=new ScrollView(this);LinearLayout p=page("GPX Lab","Avant / après du nettoyage et du recalage GPX.");List<File> files=store.routeFiles();if(files.isEmpty()){p.addView(infoCard("Aucun GPX","Importe ou enregistre une tournée pour afficher un avant / après."));sv.addView(p);return sv;}File f=files.get(0);String wanted=prefs.getString("gpx_lab_file",null);if(wanted!=null)for(File x:files)if(x.getName().equals(wanted)){f=x;break;}final File selected=f;RouteStore.Summary after=store.parse(selected);int input=prefs.getInt("import_input_"+selected.getName(),after.points.size()),output=prefs.getInt("import_output_"+selected.getName(),after.points.size()),invalid=prefs.getInt("import_invalid_"+selected.getName(),0),dup=prefs.getInt("import_duplicates_"+selected.getName(),0),simp=prefs.getInt("import_simplified_"+selected.getName(),Math.max(0,input-output));boolean matched=prefs.getBoolean("import_matched_"+selected.getName(),false);int confidence=prefs.getInt("import_confidence_"+selected.getName(),matched?0:100),generated=prefs.getInt("import_generated_steps_"+selected.getName(),0);
        TextView choose=pill("Fichier : "+store.displayName(selected)+"  ▾",SURFACE2);choose.setOnClickListener(v->{String[] labels=new String[files.size()];for(int i=0;i<files.size();i++)labels[i]=store.displayName(files.get(i));new AlertDialog.Builder(this).setTitle("GPX à analyser").setItems(labels,(d,w)->{prefs.edit().putString("gpx_lab_file",files.get(w).getName()).apply();showTab("gpxlab",false);}).show();});p.addView(choose,new LinearLayout.LayoutParams(-1,dp(50)));p.addView(section("Avant / après"));LinearLayout compare=new LinearLayout(this);compare.addView(bigMetric(String.valueOf(input),"AVANT\npoints bruts",PEACH),new LinearLayout.LayoutParams(0,dp(112),1));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,dp(112),1);cp.leftMargin=dp(9);compare.addView(bigMetric(String.valueOf(output),"APRÈS\npoints utiles",GREEN),cp);p.addView(compare);TextView delta=infoCard("Transformation","−"+Math.max(0,input-output)+" points • "+invalid+" invalides • "+dup+" doublons • "+simp+" simplifiés");LinearLayout.LayoutParams dl=new LinearLayout.LayoutParams(-1,-2);dl.topMargin=dp(9);p.addView(delta,dl);p.addView(section("Pipeline"));p.addView(stage("01","Validation GPS",invalid+" points rejetés",invalid>0?PEACH:GREEN));p.addView(stage("02","Déduplication",dup+" points trop proches supprimés",dup>0?BLUE:GREEN));p.addView(stage("03","Simplification conservatrice",simp+" points retirés sans casser les retours",MAUVE));p.addView(stage("04","Recalage routier",matched?("Actif • confiance "+confidence+" % • "+generated+" étapes ajoutées"):"Non appliqué / trace propre conservée",matched?TEAL:MUTED));p.addView(section("Contrôles"));p.addView(toggleRow("Optimiseur GPX","OFF = import brut : aucun point supprimé, simplifié ou recalé. ON = nettoyage et recalage routier.","gpx_match_roads",true,()->{}));sv.addView(p);return sv;
    }

    private View morePage(){ScrollView sv=new ScrollView(this);LinearLayout p=page("Plus","Les outils utiles, à portée de main.");
        menu(p,"Heures travaillées","Saisie et total du mois",()->showTab("hours",true));menu(p,"Réglages","Carte, apparence et guidage",()->showTab("settings",true));
        menu(p,"Cartes hors ligne","Packs régionaux français",this::offlineMenu);menu(p,"Exporter le diagnostic","Rapport technique sans trace GPS",this::exportDiagnostics);
        TextView advanced=pill("Avancé  ⌄",SURFACE2);p.addView(advanced,new LinearLayout.LayoutParams(-1,dp(52)));LinearLayout extra=new LinearLayout(this);extra.setOrientation(LinearLayout.VERTICAL);extra.setVisibility(View.GONE);menu(extra,"GPX Lab","Analyse et nettoyage des imports",()->showTab("gpxlab",true));p.addView(extra);advanced.setOnClickListener(v->extra.setVisibility(extra.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE));sv.addView(p);return sv;}
    private void menu(LinearLayout p,String title,String subtitle,Runnable action){LinearLayout row=settingsRow(title,subtitle);row.setMinimumHeight(dp(64));row.setOnClickListener(v->action.run());p.addView(row);}
    private View settingsPage(){ScrollView sv=new ScrollView(this);LinearLayout p=page("Réglages","Une interface lisible pendant la collecte.");
        p.addView(choiceRow("Couleur d’accent","accent_color",new int[]{MAUVE,BLUE,GREEN,PEACH,TEAL},new String[]{"Mauve","Bleu","Vert","Pêche","Sarcelle"},MAUVE,()->{accent=prefs.getInt("accent_color",MAUVE);rebuildChrome();if(modern!=null)modern.refreshStyle();}));
        p.addView(stringChoiceRow("Fond de carte","map_appearance",new String[]{"light","dark"},new String[]{"Clair minimaliste","Sombre mauve"},"dark",this::applyMapStyle));
        p.addView(toggleRow("Nuit automatique","Carte sombre de 20 h à 7 h.","auto_night",false,this::applyMapStyle));
        p.addView(stringChoiceRow("Icône de position","position_icon",new String[]{"Camion","Voiture","Flèche","Point"},new String[]{"Camion","Voiture","Flèche","Point"},"Camion",()->{if(modern!=null){modern.onPause();modern.onStop();modern.onDestroy();modern=null;createModernMap();modern.onResume();}}));
        p.addView(toggleRow("Proposer le trajet jusqu’au départ","Ouvrir Google Maps ou Waze avant la collecte.","guide_to_start",true,()->{}));
        p.addView(choiceRow("Tolérance hors tracé","offroute_m",new int[]{25,35,45,60,80},new String[]{"25 m","35 m","45 m","60 m","80 m"},45,()->{}));
        p.addView(toggleRow("Rappels vocaux des repères","Annonce à moins de 55 m pendant le guidage.","voice_markers",true,()->{}));
        p.addView(toggleRow("Garder l’écran allumé","Uniquement pendant une tournée active.","keep_screen",true,this::applyRuntimePrefs));
        TextView advanced=pill("Avancé  ⌄",SURFACE2);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(52));ap.topMargin=dp(16);p.addView(advanced,ap);
        LinearLayout extra=new LinearLayout(this);extra.setOrientation(LinearLayout.VERTICAL);extra.setVisibility(View.GONE);
        extra.addView(toggleRow("Animations","Transitions et retours tactiles.","animations",true,()->{}));
        extra.addView(choiceRow("Précision GPS maximale","record_accuracy",new int[]{20,30,45,60},new String[]{"20 m","30 m","45 m","60 m"},45,()->{}));
        extra.addView(toggleRow("Optimiser les imports GPX","Recalage routier : peut modifier la trace d’origine.","gpx_match_roads",false,()->{}));
        menu(extra,"Exporter le diagnostic","À joindre si Routix rencontre un problème",this::exportDiagnostics);p.addView(extra);advanced.setOnClickListener(v->extra.setVisibility(extra.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE));sv.addView(p);return sv;}
    private void showMapStyleMenu(){new AlertDialog.Builder(this).setTitle("Fond de carte").setItems(new String[]{"Clair minimaliste","Sombre mauve"},(d,w)->{prefs.edit().putString("map_appearance",w==0?"light":"dark").putBoolean("auto_night",false).apply();applyMapStyle();}).show();}
    private void offlineMenu(){List<String> labels=new ArrayList<>();labels.add("Carte en ligne");for(FranceOfflineManager.Pack p:FranceOfflineManager.PACKS)labels.add(p.label+(FranceOfflineManager.isInstalled(this,p)?" • installé":" • télécharger"));new AlertDialog.Builder(this).setTitle("Cartes hors ligne").setItems(labels.toArray(new String[0]),(d,w)->{if(w==0){prefs.edit().remove("offline_pack").apply();applyMapStyle();return;}FranceOfflineManager.Pack pack=FranceOfflineManager.PACKS.get(w-1);if(FranceOfflineManager.isInstalled(this,pack)){prefs.edit().putString("offline_pack",pack.id).apply();applyMapStyle();toast("Carte hors ligne : "+pack.label);}else try{FranceOfflineManager.download(this,pack);toast("Téléchargement lancé. Sélectionne le pack une fois terminé.");}catch(RuntimeException e){DiagnosticLog.error("offline download",e);toast("Téléchargement indisponible");}}).show();}
    private void exportDiagnostics(){try{File f=DiagnosticLog.export(this);Intent i=new Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_STREAM,FileProvider.getUriForFile(this,getPackageName()+".files",f)).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Rapport Routix"));}catch(Exception e){DiagnosticLog.error("export diagnostic",e);toast("Export impossible");}}

    private View choiceRow(String title,String key,int[] values,String[] labels,int def,Runnable changed){int cur=prefs.getInt(key,def),idx=0;for(int i=0;i<values.length;i++)if(values[i]==cur){idx=i;break;}final int selected=idx;LinearLayout row=settingsRow(title,labels[selected]);row.setOnClickListener(v->new AlertDialog.Builder(this).setTitle(title).setSingleChoiceItems(labels,selected,(d,w)->{prefs.edit().putInt(key,values[w]).apply();d.dismiss();if(changed!=null)changed.run();showTab("settings",false);}).show());return row;}
    private View stringChoiceRow(String title,String key,String[] values,String[] labels,String def,Runnable changed){String cur=prefs.getString(key,def);int found=0;for(int i=0;i<values.length;i++)if(values[i].equals(cur)){found=i;break;}final int idx=found;LinearLayout row=settingsRow(title,labels[idx]);row.setOnClickListener(v->new AlertDialog.Builder(this).setTitle(title).setSingleChoiceItems(labels,idx,(d,w)->{prefs.edit().putString(key,values[w]).apply();d.dismiss();if(changed!=null)changed.run();showTab("settings",false);}).show());return row;}
    private LinearLayout settingsRow(String title,String value){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(14),dp(12),dp(12),dp(12));row.setBackground(glass(SURFACE,20));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.addView(text(title,14,Typeface.BOLD,TEXT));tx.addView(text(value,11,Typeface.NORMAL,MUTED));row.addView(tx,new LinearLayout.LayoutParams(0,-2,1));TextView arrow=text("⌄",18,Typeface.BOLD,MUTED);arrow.setGravity(Gravity.CENTER);row.addView(arrow,new LinearLayout.LayoutParams(dp(28),dp(34)));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(8);row.setLayoutParams(lp);return row;}
    private View toggleRow(String title,String sub,String key,boolean def,Runnable changed){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(14),dp(12),dp(12),dp(12));row.setBackground(glass(SURFACE,20));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.addView(text(title,14,Typeface.BOLD,TEXT));tx.addView(text(sub,11,Typeface.NORMAL,MUTED));row.addView(tx,new LinearLayout.LayoutParams(0,-2,1));TextView state=toggleCapsule(prefs.getBoolean(key,def));row.addView(state,new LinearLayout.LayoutParams(dp(54),dp(32)));row.setOnClickListener(v->{press(v);boolean on=!prefs.getBoolean(key,def);prefs.edit().putBoolean(key,on).apply();state.setText(on?"ON":"OFF");state.setTextColor(on?BG:MUTED);state.setBackground(glass(on?accent:SURFACE2,16));if(changed!=null)changed.run();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(8);row.setLayoutParams(lp);return row;}
    private TextView toggleCapsule(boolean on){TextView t=text(on?"ON":"OFF",10,Typeface.BOLD,on?BG:MUTED);t.setGravity(Gravity.CENTER);t.setBackground(glass(on?accent:SURFACE2,16));return t;}

    private void startRecording(){if(tracker==null||!tracker.beginRecording()){ensureLocation();toast("Attends le GPS et autorise la localisation précise");return;}showTab("record",true);}
    private void finishRecording(){if(tracker==null||tracker.points.size()<2){toast("Pas assez de points GPS");return;}toast("Sauvegarde de la tournée…");tracker.finish(f->{if(isDestroyed())return;toast(f==null?"Échec : brouillon conservé, réessaie":"Tournée sauvegardée");showTab(f==null?"record":"routes",true);});}
    private void togglePause(){if(tracker!=null)tracker.togglePause();showTab("record",false);}
    private void addEvent(String type,String label){if(tracker==null||!recording||paused||lastLocation==null){toast("Enregistrement GPS requis");return;}tracker.addEvent(type,label);}
    private void addGuidanceFlag(String type,String label){if(tracker==null||!guiding||lastLocation==null){toast("GPS ou tournée indisponible");return;}tracker.addGuidanceEvent(type,label);toast("Repère ajouté");}
    private void setFlagEnabled(boolean on){for(TextView t:new TextView[]{reverseButton,twoSidesButton,pauseButton})if(t!=null){t.setEnabled(on);t.setAlpha(on?1:.38f);}}
    private void offerDraftRecovery(){RouteStore.Summary draft=store.draftSummary();new AlertDialog.Builder(this).setTitle("Tournée interrompue").setMessage(draft.points.size()+" points récupérables.").setNegativeButton("Plus tard",null).setPositiveButton("Récupérer",(d,w)->{if(tracker!=null)tracker.recoverDraft(draft);showTab("record",true);}).show();}

    private void importGpx(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,IMPORT_GPX);}
    @Override protected void onActivityResult(int r,int result,Intent data){super.onActivityResult(r,result,data);if(r==IMPORT_GPX&&result==RESULT_OK&&data!=null&&data.getData()!=null){Uri u=data.getData();toast("Analyse du GPX…");new Thread(()->{File f=store.importGpx(u);runOnUiThread(()->{toast(f==null?"Import impossible":"GPX importé");if(f!=null)prefs.edit().putString("gpx_lab_file",f.getName()).apply();if(!isDestroyed())showTab("routes",false);});},"routix-import").start();}}

    private void startGuidance(RouteStore.Summary s){
        if(s==null||s.points.size()<2||tracker==null||!tracker.ready){toast("Trace ou GPS indisponible");return;}
        tracker.beginGuidance(s);guidanceCameraFollow=true;headingUp=true;if(modern!=null)modern.heading(true);showTab("map",true);drawRemaining(tracker.guidanceState);recenter();
        if(lastLocation!=null&&prefs.getBoolean("guide_to_start",true)){RouteStore.Point first=s.points.get(0);float[] d=new float[1];Location.distanceBetween(lastLocation.getLatitude(),lastLocation.getLongitude(),first.lat,first.lon,d);if(d[0]>100)new AlertDialog.Builder(this).setTitle("Rejoindre le départ ?").setMessage("Le suivi de tournée reste actif pendant la navigation externe.").setNegativeButton("Rester ici",null).setPositiveButton("Aller au départ",(dialog,w)->DepartureNavigation.open(this,lastLocation,first)).show();}
    }
    private void updateRouteGuidance(Location l){if(!guiding||tracker==null)return;GuidanceEngine.State state=tracker.guidanceState;if(state==null){drawRemaining(null);return;}drawRemaining(state);
        if(guideDistance!=null)guideDistance.setText(formatDistance(state.remainingM)+"\nRESTANT");if(guideProgress!=null)guideProgress.setText(state.progressPercent+" %\nPROGRESSION");
        if(guideTitle!=null)guideTitle.setText(state.poorAccuracy?"GPS imprécis":state.finished?"Tournée terminée":state.offRoute?"Rejoins le tracé":"Suis les flèches");
        if(guideSubtitle!=null)guideSubtitle.setText(state.poorAccuracy?"Progression conservée en attendant un GPS fiable":state.nextEvent!=null?state.nextEvent.label+" · "+formatDistance(state.distanceToNextEventM):"Le tracé parcouru disparaît derrière toi");followCamera(l);
    }
    private void drawRemaining(GuidanceEngine.State state){if(!guiding||guidingRoute==null||!"map".equals(selectedTab))return;boolean erase=prefs.getBoolean("erase_passed",true);int start=!erase||state==null?0:Math.max(0,Math.min(guidingRoute.points.size()-2,state.nearestIndex));List<GeoPoint> pts=new ArrayList<>();if(state!=null&&erase&&Double.isFinite(state.position.lat))pts.add(new GeoPoint(state.position.lat,state.position.lon));for(int i=start+(erase&&state!=null?1:0);i<guidingRoute.points.size();i++){RouteStore.Point p=guidingRoute.points.get(i);pts.add(new GeoPoint(p.lat,p.lon));}if(modern!=null){modern.setRoute(pts);modern.setEvents(guidingRoute.events);}remainingLine.setPoints(offline?pts:Collections.emptyList());remainingLine.getOutlinePaint().setColor(routeColor());remainingLine.getOutlinePaint().setStrokeWidth(dp(prefs.getInt("route_width",10)));{if(offline&&prefs.getBoolean("route_arrows",true))routeArrows.setPoints(pts);else routeArrows.setPoints(new ArrayList<>());}map.invalidate();}
    private void redrawGuidance(){if(tracker!=null)drawRemaining(tracker.guidanceState);}
    private void resumeGuidanceHere(){if(tracker==null||!tracker.reposition()){toast("Rapproche-toi du tracé avec un GPS précis");return;}guidanceCameraFollow=true;recenter();toast("Progression reprise au point le plus proche");}
    private void stopGuidance(){if(tracker!=null)tracker.stopGuidance();remainingLine.setPoints(new ArrayList<>());routeArrows.setPoints(new ArrayList<>());if(modern!=null){modern.setRoute(new ArrayList<>());modern.setEvents(Collections.emptyList());}showTab("map",true);}
    private void followCamera(Location l){if(l==null)return;if(modern!=null)modern.update(l,guiding);if(offline&&guidanceCameraFollow){map.getController().animateTo(new GeoPoint(l.getLatitude(),l.getLongitude()));if(headingUp&&l.hasBearing()&&l.getSpeed()>.9f)map.setMapOrientation((float)MapStyles.smoothBearing(map.getMapOrientation(),360-l.getBearing()));}}
    public void onLocationChanged(@NonNull Location l){lastLocation=l;if(headerSpeed!=null)headerSpeed.update(l);if(guiding)updateRouteGuidance(l);else if(modern!=null)modern.update(l,false);if(offline){if(offlinePosition==null){offlinePosition=new org.osmdroid.views.overlay.Marker(map);offlinePosition.setIcon(new android.graphics.drawable.BitmapDrawable(getResources(),createPositionIcon(prefs.getString("position_icon","Camion"))));offlinePosition.setAnchor(.5f,.5f);map.getOverlays().add(offlinePosition);}offlinePosition.setPosition(new GeoPoint(l.getLatitude(),l.getLongitude()));map.invalidate();}}
    private org.osmdroid.views.overlay.Marker offlinePosition;
    private void ensureLocation(){if(ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)ActivityCompat.requestPermissions(this,new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},LOCATION_PERMISSION);else{ensureNotificationPermission();if(tracker!=null&&visible)tracker.observe(this::syncTracking);}}
    private void ensureNotificationPermission(){if(android.os.Build.VERSION.SDK_INT<33||ContextCompat.checkSelfPermission(this,Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED||prefs.getBoolean("notification_permission_prompted",false))return;prefs.edit().putBoolean("notification_permission_prompted",true).apply();ActivityCompat.requestPermissions(this,new String[]{Manifest.permission.POST_NOTIFICATIONS},NOTIFICATION_PERMISSION);}
    @Override public void onRequestPermissionsResult(int r,@NonNull String[] p,@NonNull int[] g){super.onRequestPermissionsResult(r,p,g);if(r==LOCATION_PERMISSION&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)ensureLocation();}
    private void recenter(){guidanceCameraFollow=true;if(lastLocation==null){toast("GPS en attente");return;}if(modern!=null)modern.recenter(lastLocation,guiding);map.getController().animateTo(new GeoPoint(lastLocation.getLatitude(),lastLocation.getLongitude()));map.getController().setZoom(18.0);}
    private final android.content.ServiceConnection connection=new android.content.ServiceConnection(){
        public void onServiceConnected(android.content.ComponentName name,android.os.IBinder binder){tracker=((TrackingService.LocalBinder)binder).service();if(visible)tracker.observe(RoutixActivity.this::syncTracking);}
        public void onServiceDisconnected(android.content.ComponentName name){tracker=null;DiagnosticLog.info("tracking service disconnected");}
    };
    private void syncTracking(){if(tracker==null||!tracker.ready||isDestroyed())return;boolean changed=recording!=tracker.recording||paused!=tracker.paused||guiding!=(tracker.guidance!=null);recording=tracker.recording;paused=tracker.paused;recordingStarted=tracker.started;recordedDistance=tracker.distance;guiding=tracker.guidance!=null;guidingRoute=tracker.route;guidance=tracker.guidance;
        // Copy only the counters into the existing recording UI; service owns the point lists.
        if(recordDistance!=null)recordDistance.setText(formatDistance(recordedDistance)+"\nDISTANCE");if(recordPoints!=null)recordPoints.setText(tracker.points.size()+"\nPOINTS");if(recordEvents!=null)recordEvents.setText(tracker.events.size()+"\nREPÈRES");
        if(changed)showTab(selectedTab,false);if(recordMain!=null)recordMain.setEnabled(!tracker.saving);if(tracker.location!=null)onLocationChanged(tracker.location);else if(guiding)drawRemaining(tracker.guidanceState);applyRuntimePrefs();
        if(!recoveryOffered){recoveryOffered=true;if(!recording&&store.hasDraft())offerDraftRecovery();}
    }

    private LinearLayout page(String title,String sub){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);int pad=20;p.setPadding(dp(pad),dp(prefs.getBoolean("compact_ui",false)?12:18),dp(pad),dp(28));p.addView(text(title,30,Typeface.BOLD,TEXT));TextView s=text(sub,12,Typeface.NORMAL,MUTED);s.setPadding(0,dp(4),0,dp(14));p.addView(s);return p;}
    private TextView section(String s){TextView t=text(s.toUpperCase(Locale.ROOT),10,Typeface.BOLD,accent);t.setPadding(0,dp(20),0,dp(8));return t;}
    private TextView text(String s,float size,int style,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setTypeface(Typeface.create("sans-serif",style));t.setIncludeFontPadding(false);return t;}
    private TextView pill(String s,int color){TextView t=text(s,13,Typeface.BOLD,(color==accent||color==GREEN||color==PEACH||color==RED)?BG:TEXT);t.setGravity(Gravity.CENTER);t.setBackground(glass(color,20));t.setElevation(dp(2));return t;}
    private TextView metric(String value,String label){TextView t=text(value+"\n"+label,13,Typeface.BOLD,TEXT);t.setGravity(Gravity.CENTER);t.setBackground(glass(SURFACE,20));return t;}
    private TextView bigMetric(String value,String label,int color){TextView t=text(value+"\n"+label,18,Typeface.BOLD,TEXT);t.setGravity(Gravity.CENTER);t.setBackground(glass(Color.argb(160,Color.red(color),Color.green(color),Color.blue(color)),24));return t;}
    private TextView icon(String s){TextView t=text(s,19,Typeface.BOLD,TEXT);t.setGravity(Gravity.CENTER);t.setBackground(glass(SURFACE2,18));return t;}
    private TextView infoCard(String title,String body){TextView t=text(title+"\n"+body,12,Typeface.NORMAL,MUTED);t.setPadding(dp(14),dp(12),dp(14),dp(12));t.setBackground(glass(SURFACE,20));return t;}
    private View stage(String number,String title,String sub,int color){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(12),dp(10),dp(12),dp(10));r.setBackground(glass(SURFACE,18));TextView n=text(number,12,Typeface.BOLD,color);n.setGravity(Gravity.CENTER);n.setBackground(glass(SURFACE2,14));r.addView(n,new LinearLayout.LayoutParams(dp(42),dp(42)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.setPadding(dp(11),0,0,0);tx.addView(text(title,13,Typeface.BOLD,TEXT));tx.addView(text(sub,11,Typeface.NORMAL,MUTED));r.addView(tx,new LinearLayout.LayoutParams(0,-2,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(7);r.setLayoutParams(lp);return r;}
    private View summaryStat(String label,String value){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setGravity(Gravity.CENTER);c.addView(text(value,13,Typeface.BOLD,TEXT));c.addView(text(label,9,Typeface.BOLD,MUTED));return c;}
    private GradientDrawable glass(int color,float radius){int base=96;String style=prefs==null?"apple":prefs.getString("ui_style","apple");if("contrast".equals(style))base=Math.min(98,base+10);if("minimal".equals(style))radius*=.78f;int aa=Math.max(38,Math.min(100,base))*255/100;int c1=Color.argb(Math.min(255,aa+20),Color.red(color),Color.green(color),Color.blue(color));int c2=Color.argb(aa,Color.red(color),Color.green(color),Color.blue(color));GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{c1,c2});g.setCornerRadius(dp(radius));g.setStroke(dp(1),Color.argb("contrast".equals(style)?70:42,255,255,255));return g;}
    private void press(View v){if(v==null)return;if(prefs.getBoolean("haptics",true))v.performHapticFeedback(HapticFeedbackConstants.KEYBOARD_TAP);if(prefs.getBoolean("animations",true))v.animate().scaleX(.94f).scaleY(.94f).setDuration(70).withEndAction(()->v.animate().scaleX(1).scaleY(1).setDuration(150).start()).start();}
    private int animDuration(){return prefs.getInt("anim_speed",220);}
    private int routeColor(){return prefs.getInt("route_color",BLUE);}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    private int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);}
    private static String formatDistance(double m){return m<1000?Math.round(m)+" m":String.format(Locale.FRANCE,"%.1f km",m/1000d);}
    private static String formatMinutes(int m){return String.format(Locale.FRANCE,"%dh%02d",m/60,m%60);}
    private static String formatDuration(long ms){long min=Math.max(0,ms/60000);return String.format(Locale.FRANCE,"%dh%02d",min/60,min%60);}
    private static String formatDate(long ms){return new SimpleDateFormat("dd MMM yyyy • HH:mm",Locale.FRANCE).format(new Date(ms));}
    private static String timeLabel(int minutes){int m=((minutes%1440)+1440)%1440;return String.format(Locale.FRANCE,"%02d:%02d",m/60,m%60);}
    private static int parsePositive(String s){try{return Math.max(0,Integer.parseInt(s.trim()));}catch(Exception e){return 0;}}
    private static int parseClock(String raw){if(raw==null)return-1;String s=raw.trim().replace("h",":").replace("H",":");try{int h,m;if(s.contains(":")){String[] p=s.split(":");if(p.length<2)return-1;h=Integer.parseInt(p[0]);m=Integer.parseInt(p[1]);}else{String d=s.replaceAll("[^0-9]","");if(d.length()<3||d.length()>4)return-1;int v=Integer.parseInt(d);h=v/100;m=v%100;}return h>=0&&h<24&&m>=0&&m<60?h*60+m:-1;}catch(Exception e){return-1;}}
    private static int nowMinutes(){Calendar c=Calendar.getInstance();return c.get(Calendar.HOUR_OF_DAY)*60+c.get(Calendar.MINUTE);}
    private static String todayKey(){return new SimpleDateFormat("yyyy-MM-dd",Locale.FRANCE).format(new Date());}
    private static String dayLabel(String date){try{return new SimpleDateFormat("EEEE d MMMM",Locale.FRANCE).format(new SimpleDateFormat("yyyy-MM-dd",Locale.FRANCE).parse(date));}catch(Exception e){return date;}}
    private static String monthLabel(String month){try{return new SimpleDateFormat("MMMM yyyy",Locale.FRANCE).format(new SimpleDateFormat("yyyy-MM",Locale.FRANCE).parse(month));}catch(Exception e){return month;}}

    private void rebuildChrome(){if(root==null)return;if(topBar!=null)root.removeView(topBar);if(dock!=null)root.removeView(dock);topBar=buildTopBar();dock=buildDock();root.addView(topBar);root.addView(dock);topBar.bringToFront();contentHost.bringToFront();dock.bringToFront();updateDock();positionChrome();applyRuntimePrefs();}
    private void applyRuntimePrefs(){if((recording||guiding)&&prefs.getBoolean("keep_screen",true))getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);else getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);if(mapLogo!=null)mapLogo.setVisibility("map".equals(selectedTab)&&false?View.VISIBLE:View.GONE);if(headerSpeed!=null)headerSpeed.setVisibility(prefs.getBoolean("show_speed",true)?View.VISIBLE:View.GONE);}
    private void positionChrome(){if(root==null||topBar==null||dock==null||contentHost==null)return;boolean compact=false;int top=systemTop+dp(8),bottom=systemBottom+dp(8),topH=dp(compact?58:64),dockH=dp(compact?62:70);FrameLayout.LayoutParams hp=new FrameLayout.LayoutParams(-1,topH,Gravity.TOP);hp.setMargins(dp(10),top,dp(10),0);topBar.setLayoutParams(hp);FrameLayout.LayoutParams dpv=new FrameLayout.LayoutParams(-1,dockH,Gravity.BOTTOM);dpv.setMargins(dp(10),0,dp(10),bottom);dock.setLayoutParams(dpv);if(modern!=null)modern.inset(top+topH);if(mapLogo!=null){FrameLayout.LayoutParams ml=new FrameLayout.LayoutParams(dp(52),dp(52),Gravity.TOP|Gravity.START);ml.setMargins(dp(14),top+topH+dp(10),0,0);mapLogo.setLayoutParams(ml);}if("map".equals(selectedTab)){FrameLayout.LayoutParams cp=new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM);cp.setMargins(dp(10),0,dp(10),bottom+dockH+dp(8));contentHost.setLayoutParams(cp);}else{FrameLayout.LayoutParams cp=new FrameLayout.LayoutParams(-1,-1);cp.setMargins(0,top+topH+dp(8),0,bottom+dockH+dp(8));contentHost.setLayoutParams(cp);}}

    private void createModernMap(){if(modern!=null)return;modern=new ModernMapController(this,root,createPositionIcon(prefs.getString("position_icon","Camion")),mapState);modern.onStart();modern.setVisible(!offline&&"map".equals(selectedTab));positionChrome();}
    @Override protected void onStart(){super.onStart();if(modern==null)createModernMap();else modern.onStart();bound=bindService(new Intent(this,TrackingService.class),connection,BIND_AUTO_CREATE);}
    @Override protected void onResume(){super.onResume();visible=true;if(map!=null&&offline)map.onResume();if(modern!=null)modern.onResume();if(tracker!=null)tracker.observe(this::syncTracking);}
    @Override protected void onPause(){visible=false;if(tracker!=null)tracker.observe(null);if(modern!=null)modern.onPause();if(map!=null)map.onPause();super.onPause();}
    @Override protected void onStop(){visible=false;if(tracker!=null)tracker.observe(null);if(bound){unbindService(connection);bound=false;tracker=null;}if(modern!=null)modern.onStop();super.onStop();}
    @Override protected void onSaveInstanceState(Bundle out){super.onSaveInstanceState(out);if(modern!=null)modern.onSaveInstanceState(out);}
    @Override public void onLowMemory(){super.onLowMemory();if(modern!=null)modern.onLowMemory();if(map!=null)map.getTileProvider().clearTileCache();}
    @Override protected void onDestroy(){guidanceSession++;if(modern!=null)modern.onDestroy();if(map!=null)map.onDetach();super.onDestroy();}
}
