package com.routix.app;
import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;
/** Explicit, opt-in route improvement. Never writes RouteStore or mutates the source route. */
final class RouteImprovementEngine{
 interface Progress{void onProgress(int percent,String label);}
 static final class Result{final List<RouteStore.Point> points;final double beforeM,afterM;final int requiredArcs;Result(List<RouteStore.Point>p,double b,double a,int r){points=p;beforeM=b;afterM=a;requiredArcs=r;}double gainM(){return beforeM-afterM;}double gainPct(){return beforeM<=0?0:gainM()*100d/beforeM;}}
 static final class Edge{final long way;final String highway;final boolean oneway;final List<RouteStore.Point> p;Edge(long w,String h,boolean o,List<RouteStore.Point>x){way=w;highway=h;oneway=o;p=x;}Edge reverse(){List<RouteStore.Point>x=new ArrayList<>(p);Collections.reverse(x);return new Edge(way,highway,oneway,x);}}
 static Result improve(RouteStore.Summary src,Progress cb)throws Exception{
  if(src==null||src.points.size()<2)throw new IOException("Tournée vide");if(src.points.size()>25000)throw new IOException("Tournée trop grande pour l’amélioration mobile");
  progress(cb,5,"Analyse de la zone");double[] b=bounds(src.points);String q="[out:json][timeout:25];way[highway]("+b[0]+","+b[1]+","+b[2]+","+b[3]+");out tags geom;";
  JSONObject osm=json(post("https://overpass-api.de/api/interpreter",q,"application/x-www-form-urlencoded"));progress(cb,25,"Construction du graphe OSM");
  List<Edge> required=new ArrayList<>();JSONArray els=osm.optJSONArray("elements");if(els!=null)for(int i=0;i<els.length();i++){JSONObject w=els.getJSONObject(i),tags=w.optJSONObject("tags");JSONArray geom=w.optJSONArray("geometry");if(tags==null||geom==null||geom.length()<2)continue;String h=tags.optString("highway","");if(!drivable(h))continue;List<RouteStore.Point> pts=new ArrayList<>();for(int j=0;j<geom.length();j++){JSONObject n=geom.getJSONObject(j);pts.add(new RouteStore.Point(n.getDouble("lat"),n.getDouble("lon"),0,0));}if(!touches(src.points,pts,32))continue;String ow=tags.optString("oneway","no");boolean reverse="-1".equals(ow),oneway="yes".equals(ow)||"1".equals(ow)||"true".equals(ow)||reverse||"roundabout".equals(tags.optString("junction"));Edge e=new Edge(w.getLong("id"),h,oneway,reverse?new Edge(0,h,true,pts).reverse().p:pts);required.add(e);if(major(h)&&!oneway)required.add(e.reverse());}
  if(required.isEmpty())throw new IOException("Aucune rue OSM correspondante trouvée");if(required.size()>450)throw new IOException("Tournée trop grande : "+required.size()+" segments obligatoires");
  progress(cb,40,"Optimisation des passages");RouteStore.Point depot=src.points.get(0);List<Edge> order=order(required,depot);order=twoOpt(order,depot);List<RouteStore.Point> out=new ArrayList<>();RouteStore.Point here=depot;out.add(here);int done=0;
  for(Edge e:order){RouteStore.Point a=e.p.get(0);if(dist(here,a)>20)append(out,osrm(here,a));append(out,e.p);here=e.p.get(e.p.size()-1);done++;progress(cb,40+(int)(50d*done/order.size()),"Routage "+done+"/"+order.size());}
  if(dist(here,depot)>15)append(out,osrm(here,depot));progress(cb,95,"Vérification");double after=distance(out);if(out.size()<2)throw new IOException("Calcul incomplet");progress(cb,100,"Aperçu prêt");return new Result(out,src.distanceM,after,required.size());
 }
 private static List<Edge> twoOpt(List<Edge> seed,RouteStore.Point start){List<Edge> best=new ArrayList<>(seed);double score=connectorCost(best,start);boolean changed=true;for(int pass=0;pass<4&&changed;pass++){changed=false;for(int i=0;i<best.size()-1;i++)for(int j=i+1;j<best.size();j++){List<Edge>x=new ArrayList<>(best);Collections.swap(x,i,j);double s=connectorCost(x,start);if(s+1<score){best=x;score=s;changed=true;}}}return best;}
 private static double connectorCost(List<Edge>x,RouteStore.Point start){double n=0;RouteStore.Point at=start;for(Edge e:x){n+=dist(at,e.p.get(0));at=e.p.get(e.p.size()-1);}return n+dist(at,start);}
 private static List<Edge> order(List<Edge> in,RouteStore.Point start){List<Edge> left=new ArrayList<>(in),out=new ArrayList<>();RouteStore.Point at=start;while(!left.isEmpty()){int bi=0;double bd=Double.MAX_VALUE;for(int i=0;i<left.size();i++){double d=dist(at,left.get(i).p.get(0));if(d<bd){bd=d;bi=i;}}Edge e=left.remove(bi);out.add(e);at=e.p.get(e.p.size()-1);}return out;}
 private static List<RouteStore.Point> osrm(RouteStore.Point a,RouteStore.Point b)throws Exception{String u="https://router.project-osrm.org/route/v1/driving/"+a.lon+","+a.lat+";"+b.lon+","+b.lat+"?overview=full&geometries=geojson&steps=false";JSONObject j=json(get(u));if(!"Ok".equals(j.optString("code")))throw new IOException("OSRM ne trouve pas de liaison");JSONArray c=j.getJSONArray("routes").getJSONObject(0).getJSONObject("geometry").getJSONArray("coordinates");List<RouteStore.Point> r=new ArrayList<>();for(int i=0;i<c.length();i++){JSONArray p=c.getJSONArray(i);r.add(new RouteStore.Point(p.getDouble(1),p.getDouble(0),0,0));}return r;}
 private static boolean touches(List<RouteStore.Point> route,List<RouteStore.Point> way,double m){int step=Math.max(1,route.size()/1200);for(int i=0;i<route.size();i+=step){RouteStore.Point p=route.get(i);for(int j=0;j<way.size()-1;j++)if(segDist(p,way.get(j),way.get(j+1))<=m)return true;}return false;}
 private static double segDist(RouteStore.Point p,RouteStore.Point a,RouteStore.Point b){double k=111320,x=(p.lon-a.lon)*k*Math.cos(Math.toRadians(p.lat)),y=(p.lat-a.lat)*k,bx=(b.lon-a.lon)*k*Math.cos(Math.toRadians(p.lat)),by=(b.lat-a.lat)*k,t=(bx*bx+by*by)==0?0:(x*bx+y*by)/(bx*bx+by*by);t=Math.max(0,Math.min(1,t));return Math.hypot(x-t*bx,y-t*by);}
 private static double[] bounds(List<RouteStore.Point>p){double s=90,w=180,n=-90,e=-180;for(RouteStore.Point x:p){s=Math.min(s,x.lat);n=Math.max(n,x.lat);w=Math.min(w,x.lon);e=Math.max(e,x.lon);}double pad=.004;return new double[]{s-pad,w-pad,n+pad,e+pad};}
 private static boolean drivable(String h){return !Arrays.asList("footway","path","cycleway","steps","pedestrian","bridleway","construction","proposed").contains(h);}
 private static boolean major(String h){return "trunk".equals(h)||"primary".equals(h)||"secondary".equals(h);}
 private static void append(List<RouteStore.Point>a,List<RouteStore.Point>b){for(RouteStore.Point p:b)if(a.isEmpty()||dist(a.get(a.size()-1),p)>1)a.add(p);}
 private static double distance(List<RouteStore.Point>p){double d=0;for(int i=1;i<p.size();i++)d+=dist(p.get(i-1),p.get(i));return d;}
 private static double dist(RouteStore.Point a,RouteStore.Point b){double x=Math.toRadians(b.lon-a.lon)*Math.cos(Math.toRadians((a.lat+b.lat)/2)),y=Math.toRadians(b.lat-a.lat);return 6371000*Math.hypot(x,y);}
 private static String get(String u)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(12000);c.setReadTimeout(25000);c.setRequestProperty("User-Agent","Routix/2.1");return read(c);}
 private static String post(String u,String body,String type)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(12000);c.setReadTimeout(30000);c.setDoOutput(true);c.setRequestMethod("POST");c.setRequestProperty("Content-Type",type);c.setRequestProperty("User-Agent","Routix/2.1");try(OutputStream o=c.getOutputStream()){o.write(("data="+URLEncoder.encode(body,"UTF-8")).getBytes(StandardCharsets.UTF_8));}return read(c);}
 private static String read(HttpURLConnection c)throws Exception{int code=c.getResponseCode();InputStream in=code>=200&&code<300?c.getInputStream():c.getErrorStream();if(in==null)throw new IOException("Service réseau indisponible ("+code+")");ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[8192];for(int n;(n=in.read(b))>0;)o.write(b,0,n);if(code<200||code>=300)throw new IOException("Service réseau indisponible ("+code+")");return o.toString("UTF-8");}
 private static JSONObject json(String s)throws Exception{return new JSONObject(s);}private static void progress(Progress p,int n,String s){if(p!=null)p.onProgress(n,s);}
}