package com.routix.app;

import android.Manifest;
import android.app.AlertDialog;
import android.app.TimePickerDialog;
import android.content.Intent;
import android.content.SharedPreferences;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.location.Location;
import android.location.LocationListener;
import android.location.LocationManager;
import android.net.Uri;
import android.os.Bundle;
import android.view.Gravity;
import android.view.HapticFeedbackConstants;
import android.view.View;
import android.view.ViewGroup;
import android.view.WindowManager;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.HorizontalScrollView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.ActivityCompat;
import androidx.core.content.ContextCompat;
import androidx.core.content.FileProvider;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowCompat;
import androidx.core.view.WindowInsetsCompat;

import org.osmdroid.config.Configuration;
import org.osmdroid.tileprovider.tilesource.TileSourceFactory;
import org.osmdroid.tileprovider.tilesource.XYTileSource;
import org.osmdroid.util.BoundingBox;
import org.osmdroid.util.GeoPoint;
import org.osmdroid.views.MapView;
import org.osmdroid.views.overlay.Polyline;
import org.osmdroid.views.overlay.mylocation.GpsMyLocationProvider;
import org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;

/** Routix 3 — liquid, route-first interface with deep personalization. */
public class RoutixActivity extends AppCompatActivity implements LocationListener {
    private static final int LOCATION_PERMISSION=42, IMPORT_GPX=1337;
    private static final int BG=Color.rgb(17,17,27), SURFACE=Color.rgb(30,30,46), SURFACE2=Color.rgb(49,50,68);
    private static final int TEXT=Color.rgb(236,239,255), MUTED=Color.rgb(166,173,200), GREEN=Color.rgb(166,227,161), PEACH=Color.rgb(250,179,135), RED=Color.rgb(243,139,168), MAUVE=Color.rgb(203,166,247), BLUE=Color.rgb(137,180,250), PINK=Color.rgb(244,184,228), TEAL=Color.rgb(148,226,213);

    private SharedPreferences prefs; private RouteStore store; private WorkHoursStore hoursStore; private LocationManager lm; private Location lastLocation;
    private FrameLayout root; private MapView map; private View topBar,dock,recordSheet; private LinearLayout contentHost; private CompactSpeedometer headerSpeed; private MyLocationNewOverlay me; private ImageView mapLogo;
    private Polyline remainingLine; private RouteArrowsOverlay routeArrows; private int systemTop,systemBottom; private String selectedTab="map"; private int accent=MAUVE;
    private final List<RouteStore.Point> recordingPoints=new ArrayList<>(); private final List<RouteStore.Event> recordingEvents=new ArrayList<>();
    private boolean recording,paused,guiding; private long recordingStarted,pauseStarted,pausedTotal,lastDraftAt; private double recordedDistance;
    private TextView recordMain,recordStatus,recordDistance,recordPoints,recordEvents,reverseButton,twoSidesButton,pauseButton,guideTitle,guideDistance,guideProgress;
    private GuidanceEngine guidance; private RouteStore.Summary guidingRoute;

    @Override protected void onCreate(Bundle state){
        super.onCreate(state);WindowCompat.setDecorFitsSystemWindows(getWindow(),false);getWindow().setStatusBarColor(Color.TRANSPARENT);getWindow().setNavigationBarColor(BG);
        prefs=getSharedPreferences("routix",MODE_PRIVATE);accent=prefs.getInt("accent_color",MAUVE);store=new RouteStore(this,prefs);hoursStore=new WorkHoursStore(prefs);lm=(LocationManager)getSystemService(LOCATION_SERVICE);
        Configuration.getInstance().setUserAgentValue(getPackageName()+"/3.0 Routix");Configuration.getInstance().setOsmdroidBasePath(new File(getCacheDir(),"osmdroid"));Configuration.getInstance().setOsmdroidTileCache(new File(getCacheDir(),"osmdroid/tiles"));
        root=new FrameLayout(this);root.setBackgroundColor(BG);buildMap();topBar=buildTopBar();contentHost=new LinearLayout(this);contentHost.setOrientation(LinearLayout.VERTICAL);dock=buildDock();root.addView(topBar);root.addView(contentHost);root.addView(dock);setContentView(root);
        ViewCompat.setOnApplyWindowInsetsListener(root,(v,in)->{androidx.core.graphics.Insets b=in.getInsets(WindowInsetsCompat.Type.systemBars()|WindowInsetsCompat.Type.displayCutout());systemTop=b.top;systemBottom=b.bottom;positionChrome();return in;});ViewCompat.requestApplyInsets(root);
        showTab("map",false);ensureLocation();applyRuntimePrefs();if(store.hasDraft())root.postDelayed(this::offerDraftRecovery,450);
    }

    private void buildMap(){
        map=new MapView(this);map.setUseDataConnection(true);map.setMultiTouchControls(true);map.setMinZoomLevel(3.0);map.setMaxZoomLevel(20.0);map.getController().setZoom(17.5);applyMapStyle();root.addView(map,new FrameLayout.LayoutParams(-1,-1));
        me=new MyLocationNewOverlay(new GpsMyLocationProvider(this),map);me.setDrawAccuracyEnabled(false);map.getOverlays().add(me);
        remainingLine=new Polyline();remainingLine.getOutlinePaint().setStrokeCap(Paint.Cap.ROUND);remainingLine.getOutlinePaint().setStrokeJoin(Paint.Join.ROUND);map.getOverlays().add(remainingLine);routeArrows=new RouteArrowsOverlay();map.getOverlays().add(routeArrows);
        mapLogo=new ImageView(this);mapLogo.setImageResource(R.drawable.routix_logo);mapLogo.setScaleType(ImageView.ScaleType.CENTER_CROP);mapLogo.setPadding(dp(5),dp(5),dp(5),dp(5));mapLogo.setBackground(glass(SURFACE,18));mapLogo.setElevation(dp(9));root.addView(mapLogo,new FrameLayout.LayoutParams(dp(52),dp(52)));
    }

    private void applyMapStyle(){if(map==null)return;String style=prefs==null?"apple_dark":prefs.getString("map_style","apple_dark");if("apple_light".equals(style)){map.setTileSource(new XYTileSource("Routix Light",0,20,256,".png",new String[]{"https://a.basemaps.cartocdn.com/light_all/","https://b.basemaps.cartocdn.com/light_all/"}));}else if("terrain".equals(style)){map.setTileSource(new XYTileSource("Routix Terrain",0,19,256,".png",new String[]{"https://a.tile.opentopomap.org/","https://b.tile.opentopomap.org/"}));}else if("osm".equals(style)){map.setTileSource(TileSourceFactory.MAPNIK);}else{map.setTileSource(new XYTileSource("Routix Dark",0,20,256,".png",new String[]{"https://a.basemaps.cartocdn.com/dark_all/","https://b.basemaps.cartocdn.com/dark_all/"}));}map.setTilesScaledToDpi(prefs==null||prefs.getBoolean("tiles_scaled",true));map.setBuiltInZoomControls(prefs!=null&&prefs.getBoolean("zoom_controls",false));map.invalidate();}

    private View buildTopBar(){
        LinearLayout b=new LinearLayout(this);b.setGravity(Gravity.CENTER_VERTICAL);b.setPadding(dp(10),dp(7),dp(8),dp(7));b.setBackground(glass(SURFACE,26));b.setElevation(dp(12));
        ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.routix_logo);logo.setScaleType(ImageView.ScaleType.CENTER_CROP);logo.setVisibility(prefs.getBoolean("header_logo",true)?View.VISIBLE:View.GONE);b.addView(logo,new LinearLayout.LayoutParams(dp(46),dp(46)));
        LinearLayout brand=new LinearLayout(this);brand.setOrientation(LinearLayout.VERTICAL);brand.setPadding(dp(10),0,0,0);brand.addView(text("Routix",19,Typeface.BOLD,TEXT));brand.addView(text("terrain • tournées • guidage",10,Typeface.NORMAL,MUTED));b.addView(brand,new LinearLayout.LayoutParams(0,-2,1));
        headerSpeed=new CompactSpeedometer(this);headerSpeed.setVisibility(prefs.getBoolean("show_speed",true)?View.VISIBLE:View.GONE);b.addView(headerSpeed,new LinearLayout.LayoutParams(dp(76),dp(50)));
        TextView loc=icon("◎");loc.setOnClickListener(v->{press(v);recenter();});b.addView(loc,new LinearLayout.LayoutParams(dp(44),dp(44)));return b;
    }

    private View buildDock(){HorizontalScrollView s=new HorizontalScrollView(this);s.setHorizontalScrollBarEnabled(false);s.setFillViewport(true);s.setBackground(glass(SURFACE,27));s.setElevation(dp(14));LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER);tab(r,"⌖","Carte","map");tab(r,"●","Enregistrer","record");tab(r,"≡","Tournées","routes");tab(r,"➜","GPS","gps");tab(r,"◷","Heures","hours");tab(r,"⌘","GPX Lab","gpxlab");tab(r,"⚙","Réglages","settings");s.addView(r,new HorizontalScrollView.LayoutParams(-2,-1));return s;}
    private void tab(LinearLayout row,String glyph,String label,String key){TextView t=text(glyph+"\n"+label,10,Typeface.BOLD,MUTED);t.setGravity(Gravity.CENTER);t.setTag(key);t.setMinWidth(dp(78));t.setPadding(dp(8),dp(5),dp(8),dp(5));t.setOnClickListener(v->{press(v);if("gps".equals(key)){startActivity(new Intent(this,ClassicNavigationActivity.class));return;}showTab(key,true);});row.addView(t,new LinearLayout.LayoutParams(dp(88),-1));}

    private void showTab(String key,boolean animate){
        selectedTab=key;contentHost.removeAllViews();boolean mapMode="map".equals(key);map.setVisibility(mapMode?View.VISIBLE:View.GONE);topBar.setVisibility(View.VISIBLE);if(mapLogo!=null)mapLogo.setVisibility(mapMode&&prefs.getBoolean("map_logo",true)?View.VISIBLE:View.GONE);
        if(mapMode)contentHost.addView(mapCard());else if("record".equals(key))contentHost.addView(recordPage());else if("routes".equals(key))contentHost.addView(routesPage());else if("hours".equals(key))contentHost.addView(hoursPage());else if("gpxlab".equals(key))contentHost.addView(gpxLabPage());else if("settings".equals(key))contentHost.addView(settingsPage());recordSheet="record".equals(key)?contentHost:null;updateDock();positionChrome();
        if(animate&&prefs.getBoolean("animations",true)){int d=animDuration();contentHost.setAlpha(0);contentHost.setTranslationY(dp(prefs.getBoolean("rich_animations",true)?18:8));contentHost.setScaleX(prefs.getBoolean("rich_animations",true)?.985f:1f);contentHost.setScaleY(prefs.getBoolean("rich_animations",true)?.985f:1f);contentHost.animate().alpha(1).translationY(0).scaleX(1).scaleY(1).setDuration(d).start();}
    }
    private void updateDock(){ViewGroup r=(ViewGroup)((HorizontalScrollView)dock).getChildAt(0);for(int i=0;i<r.getChildCount();i++){TextView t=(TextView)r.getChildAt(i);boolean on=selectedTab.equals(t.getTag());t.setTextColor(on?accent:MUTED);t.setBackground(on?glass(SURFACE2,20):null);if(prefs.getBoolean("rich_animations",true))t.animate().scaleX(on?1.06f:1f).scaleY(on?1.06f:1f).setDuration(180).start();}}

    private View mapCard(){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(15),dp(13),dp(15),dp(13));card.setBackground(glass(SURFACE,26));card.setElevation(dp(9));guideTitle=text(guiding?"Suis les flèches":"Carte",18,Typeface.BOLD,TEXT);card.addView(guideTitle);TextView sub=text(guiding?"Le tracé se nettoie derrière toi en temps réel":"Choisis une tournée ou enregistre ton parcours",11,Typeface.NORMAL,MUTED);card.addView(sub);LinearLayout row=new LinearLayout(this);row.setPadding(0,dp(9),0,0);guideDistance=metric("—","RESTANT");guideProgress=metric("—","PROGRESSION");guideDistance.setVisibility(prefs.getBoolean("show_remaining",true)?View.VISIBLE:View.GONE);guideProgress.setVisibility(prefs.getBoolean("show_progress",true)?View.VISIBLE:View.GONE);row.addView(guideDistance,new LinearLayout.LayoutParams(0,dp(60),1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(60),1);p.leftMargin=dp(8);row.addView(guideProgress,p);card.addView(row);if(guiding){TextView stop=pill("Arrêter le guidage",SURFACE2);stop.setOnClickListener(v->{press(v);guiding=false;guidance=null;guidingRoute=null;remainingLine.setPoints(new ArrayList<>());routeArrows.setPoints(new ArrayList<>());showTab("map",false);});LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(46));sp.topMargin=dp(9);card.addView(stop,sp);}return card;}

    private View recordPage(){ScrollView sv=new ScrollView(this);LinearLayout p=page("Enregistrer","GPS brut, repères terrain et sauvegarde automatique.");recordStatus=text(recording?(paused?"EN PAUSE":"ENREGISTREMENT ACTIF"):"PRÊT",13,Typeface.BOLD,recording?GREEN:MUTED);p.addView(recordStatus);LinearLayout stats=new LinearLayout(this);stats.setPadding(0,dp(12),0,dp(12));recordDistance=metric(formatDistance(recordedDistance),"DISTANCE");recordPoints=metric(String.valueOf(recordingPoints.size()),"POINTS");recordEvents=metric(String.valueOf(recordingEvents.size()),"REPÈRES");stats.addView(recordDistance,new LinearLayout.LayoutParams(0,dp(68),1));stats.addView(recordPoints,new LinearLayout.LayoutParams(0,dp(68),1));stats.addView(recordEvents,new LinearLayout.LayoutParams(0,dp(68),1));p.addView(stats);recordMain=pill(recording?"Terminer et sauvegarder":"Commencer l’enregistrement",recording?RED:accent);recordMain.setOnClickListener(v->{press(v);if(recording)finishRecording();else startRecording();});p.addView(recordMain,new LinearLayout.LayoutParams(-1,dp(58)));LinearLayout flags=new LinearLayout(this);flags.setPadding(0,dp(10),0,0);reverseButton=pill("↶ Marche arrière",PEACH);twoSidesButton=pill("⇆ 2 côtés",GREEN);reverseButton.setOnClickListener(v->addEvent("REVERSE","Marche arrière"));twoSidesButton.setOnClickListener(v->addEvent("TWO_SIDES","2 côtés"));flags.addView(reverseButton,new LinearLayout.LayoutParams(0,dp(54),1));LinearLayout.LayoutParams fp=new LinearLayout.LayoutParams(0,dp(54),1);fp.leftMargin=dp(8);flags.addView(twoSidesButton,fp);p.addView(flags);pauseButton=pill(paused?"Reprendre":"Pause",SURFACE2);pauseButton.setOnClickListener(v->togglePause());LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(48));pp.topMargin=dp(8);p.addView(pauseButton,pp);setFlagEnabled(recording&&!paused);TextView info=text("Brouillon automatique toutes les "+prefs.getInt("draft_seconds",15)+" s • filtre précision "+prefs.getInt("record_accuracy",45)+" m",12,Typeface.NORMAL,MUTED);info.setPadding(0,dp(18),0,0);p.addView(info);sv.addView(p);return sv;}

    private View routesPage(){ScrollView sv=new ScrollView(this);LinearLayout p=page("Tournées","Import, guidage, plan, partage et historique.");LinearLayout actions=new LinearLayout(this);TextView imp=pill("Importer GPX",accent);imp.setOnClickListener(v->importGpx());TextView rec=pill("Nouvelle tournée",SURFACE2);rec.setOnClickListener(v->showTab("record",true));actions.addView(imp,new LinearLayout.LayoutParams(0,dp(50),1));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(0,dp(50),1);rp.leftMargin=dp(8);actions.addView(rec,rp);p.addView(actions);List<File> files=store.routeFiles();if(files.isEmpty()){TextView e=text("Aucune tournée. Importe un GPX ou enregistre ton premier parcours.",13,Typeface.NORMAL,MUTED);e.setPadding(0,dp(24),0,0);p.addView(e);}for(File f:files)p.addView(routeCard(f));sv.addView(p);return sv;}
    private View routeCard(File f){RouteStore.Summary s=store.parse(f);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(13),dp(14),dp(13));c.setBackground(glass(SURFACE,22));c.setElevation(dp(4));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.topMargin=dp(10);c.setLayoutParams(cp);c.addView(text(store.displayName(f),16,Typeface.BOLD,TEXT));c.addView(text(formatDistance(s.distanceM)+" • "+s.points.size()+" points • "+s.events.size()+" repères",11,Typeface.NORMAL,MUTED));LinearLayout a=new LinearLayout(this);a.setPadding(0,dp(10),0,0);TextView guide=pill("Guider",accent);guide.setOnClickListener(v->startGuidance(s));TextView plan=pill("Plan",SURFACE2);plan.setOnClickListener(v->PrintablePlan.open(this,s,store.displayName(f)));TextView more=pill("•••",SURFACE2);more.setOnClickListener(v->routeMenu(f,s));a.addView(guide,new LinearLayout.LayoutParams(0,dp(44),1));LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(0,dp(44),1);ap.leftMargin=dp(7);a.addView(plan,ap);LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(dp(58),dp(44));mp.leftMargin=dp(7);a.addView(more,mp);c.addView(a);return c;}
    private void routeMenu(File f,RouteStore.Summary s){String[] x={"Renommer","Dupliquer","Partager le GPX","Générer le plan","Voir dans GPX Lab","Supprimer de l’application"};new AlertDialog.Builder(this).setTitle(store.displayName(f)).setItems(x,(d,w)->{if(w==0)rename(f);else if(w==1){store.duplicate(f);showTab("routes",false);}else if(w==2)share(f);else if(w==3)PrintablePlan.open(this,s,store.displayName(f));else if(w==4){prefs.edit().putString("gpx_lab_file",f.getName()).apply();showTab("gpxlab",true);}else new AlertDialog.Builder(this).setTitle("Supprimer ?").setMessage("La copie durable dans Téléchargements/Routix reste conservée.").setNegativeButton("Annuler",null).setPositiveButton("Supprimer",(a,b)->{store.delete(f);showTab("routes",false);}).show();}).show();}
    private void rename(File f){EditText e=new EditText(this);e.setText(store.displayName(f));e.setSingleLine(true);new AlertDialog.Builder(this).setTitle("Nom de la tournée").setView(e).setNegativeButton("Annuler",null).setPositiveButton("Enregistrer",(d,w)->{store.rename(f,e.getText().toString());showTab("routes",false);}).show();}
    private void share(File f){try{Uri u=FileProvider.getUriForFile(this,getPackageName()+".files",f);Intent i=new Intent(Intent.ACTION_SEND);i.setType("application/gpx+xml");i.putExtra(Intent.EXTRA_STREAM,u);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Partager la tournée"));}catch(Exception e){toast("Partage impossible");}}

    private View hoursPage(){ScrollView sv=new ScrollView(this);LinearLayout p=page("Heures","Suivi mensuel, séparé du GPS.");String month=new SimpleDateFormat("yyyy-MM",Locale.FRANCE).format(new Date());int total=hoursStore.totalForMonth(month);TextView totalView=metric(formatMinutes(total),"CE MOIS");p.addView(totalView,new LinearLayout.LayoutParams(-1,dp(78)));TextView add=pill("Ajouter une journée",accent);add.setOnClickListener(v->addHours());LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(50));ap.topMargin=dp(10);p.addView(add,ap);for(WorkHoursStore.Entry e:hoursStore.entries()){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(12),dp(10),dp(12),dp(10));row.setBackground(glass(SURFACE,18));TextView info=text(e.date+"\n"+formatMinutes(e.netMinutes())+" • pause "+e.pauseMinutes+" min",12,Typeface.BOLD,TEXT);row.addView(info,new LinearLayout.LayoutParams(0,-2,1));TextView del=icon("×");del.setOnClickListener(v->{hoursStore.delete(e.id);showTab("hours",false);});row.addView(del,new LinearLayout.LayoutParams(dp(42),dp(42)));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(8);p.addView(row,lp);}sv.addView(p);return sv;}
    private void addHours(){final int[] v={7*60,14*60,30};TimePickerDialog start=new TimePickerDialog(this,(d,h,m)->{v[0]=h*60+m;TimePickerDialog end=new TimePickerDialog(this,(d2,h2,m2)->{v[1]=h2*60+m2;EditText pause=new EditText(this);pause.setHint("Pause en minutes");new AlertDialog.Builder(this).setTitle("Pause").setView(pause).setPositiveButton("Enregistrer",(x,w)->{try{v[2]=Integer.parseInt(pause.getText().toString());}catch(Exception ignored){}String date=new SimpleDateFormat("yyyy-MM-dd",Locale.FRANCE).format(new Date());hoursStore.add(date,v[0],v[1],v[2]);showTab("hours",false);}).show();},14,0,true);end.setTitle("Fin");end.show();},7,0,true);start.setTitle("Début");start.show();}

    private View gpxLabPage(){
        ScrollView sv=new ScrollView(this);LinearLayout p=page("GPX Lab","Visualise exactement ce que l’algorithme reçoit et ce qu’il restitue.");List<File> files=store.routeFiles();if(files.isEmpty()){p.addView(infoCard("Aucun GPX","Importe ou enregistre une tournée pour afficher un avant / après."));sv.addView(p);return sv;}
        File f=files.get(0);String wanted=prefs.getString("gpx_lab_file",null);if(wanted!=null)for(File x:files)if(x.getName().equals(wanted)){f=x;break;}final File selected=f;RouteStore.Summary after=store.parse(selected);int input=prefs.getInt("import_input_"+selected.getName(),after.points.size());int output=prefs.getInt("import_output_"+selected.getName(),after.points.size());int invalid=prefs.getInt("import_invalid_"+selected.getName(),0);int dup=prefs.getInt("import_duplicates_"+selected.getName(),0);int simp=prefs.getInt("import_simplified_"+selected.getName(),Math.max(0,input-output));boolean matched=prefs.getBoolean("import_matched_"+selected.getName(),false);int confidence=prefs.getInt("import_confidence_"+selected.getName(),matched?0:100);int generated=prefs.getInt("import_generated_steps_"+selected.getName(),0);
        TextView choose=pill("Fichier : "+store.displayName(selected)+"  ▾",SURFACE2);choose.setOnClickListener(v->{String[] labels=new String[files.size()];for(int i=0;i<files.size();i++)labels[i]=store.displayName(files.get(i));new AlertDialog.Builder(this).setTitle("GPX à analyser").setItems(labels,(d,w)->{prefs.edit().putString("gpx_lab_file",files.get(w).getName()).apply();showTab("gpxlab",false);}).show();});p.addView(choose,new LinearLayout.LayoutParams(-1,dp(50)));
        p.addView(section("Avant / après"));LinearLayout compare=new LinearLayout(this);compare.addView(bigMetric(String.valueOf(input),"AVANT\npoints bruts",PEACH),new LinearLayout.LayoutParams(0,dp(112),1));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,dp(112),1);cp.leftMargin=dp(9);compare.addView(bigMetric(String.valueOf(output),"APRÈS\npoints utiles",GREEN),cp);p.addView(compare);
        int removed=Math.max(0,input-output);TextView delta=infoCard("Transformation","−"+removed+" points • "+invalid+" invalides • "+dup+" doublons • "+simp+" simplifiés");LinearLayout.LayoutParams dl=new LinearLayout.LayoutParams(-1,-2);dl.topMargin=dp(9);p.addView(delta,dl);
        p.addView(section("Pipeline"));p.addView(stage("01","Validation GPS",invalid+" points rejetés",invalid>0?PEACH:GREEN));p.addView(stage("02","Déduplication",dup+" points trop proches supprimés",dup>0?BLUE:GREEN));p.addView(stage("03","Simplification conservatrice",simp+" points retirés sans casser les retours",MAUVE));p.addView(stage("04","Recalage routier",matched?("Actif • confiance "+confidence+" % • "+generated+" étapes ajoutées"):"Non appliqué / repli sur la trace propre",matched?TEAL:MUTED));
        p.addView(section("Contrôles algorithme"));p.addView(toggleRow("Recalage sur les routes","Pour les imports GPX uniquement. Désactive-le si tu veux respecter au millimètre la géométrie source.","gpx_match_roads",true,()->{}));p.addView(infoCard("Principe Routix","Les tournées enregistrées sur le terrain restent la vérité de référence. L’algorithme retire seulement les fixes impossibles, doublons et bruit GPS évident."));sv.addView(p);return sv;
    }

    private View settingsPage(){
        ScrollView sv=new ScrollView(this);LinearLayout p=page("Réglages","Personnalisation profonde — façon interface Apple nouvelle génération.");
        p.addView(section("Couleur & verre"));LinearLayout colors=new LinearLayout(this);for(int c:new int[]{MAUVE,BLUE,GREEN,PEACH,PINK,TEAL}){TextView b=icon("●");b.setTextColor(c);b.setOnClickListener(v->{accent=c;prefs.edit().putInt("accent_color",c).apply();rebuildChrome();showTab("settings",false);});colors.addView(b,new LinearLayout.LayoutParams(0,dp(50),1));}p.addView(colors);
        p.addView(choiceRow("Intensité du verre","glass_alpha",new int[]{58,70,82,92},new String[]{"Très transparent","Léger","Équilibré","Dense"},82,true));
        p.addView(toggleRow("Animations","Transitions, rebonds et fondus.","animations",true,()->{}));p.addView(toggleRow("Animations riches","Zoom subtil, dock vivant et cartes plus expressives.","rich_animations",true,()->{}));p.addView(choiceRow("Vitesse des animations","anim_speed",new int[]{120,220,360},new String[]{"Rapide","Fluide","Cinématique"},220,false));p.addView(toggleRow("Retour haptique","Vibration discrète sur les actions importantes.","haptics",true,()->{}));p.addView(toggleRow("Interface compacte","Réduit légèrement les marges verticales.","compact_ui",false,()->{positionChrome();}));
        p.addView(section("Carte"));p.addView(mapStyleRow());p.addView(toggleRow("Logo Routix sur la carte","Affiche le logo flottant au-dessus de la carte.","map_logo",true,this::applyRuntimePrefs));p.addView(toggleRow("Logo dans l’en-tête","Conserve aussi le logo dans la barre supérieure.","header_logo",true,this::rebuildChrome));p.addView(toggleRow("Compteur de vitesse","Affiche le compteur dans la capsule supérieure.","show_speed",true,this::rebuildChrome));p.addView(toggleRow("Flèches sur le tracé","Guidage visuel directement sur la ligne.","route_arrows",true,()->{if(guiding)drawRemaining(null);}));p.addView(toggleRow("Effacer le tracé parcouru","La partie déjà faite disparaît derrière le camion.","erase_passed",true,()->{if(guiding)drawRemaining(null);}));p.addView(toggleRow("Tuiles haute densité","Ajuste la carte à la densité de l’écran.","tiles_scaled",true,this::applyMapStyle));p.addView(toggleRow("Boutons + / − sur la carte","Désactivés par défaut pour garder une carte clean.","zoom_controls",false,this::applyMapStyle));p.addView(choiceRow("Zoom du bouton recentrer","recenter_zoom",new int[]{17,18,19,20},new String[]{"17 • large","18 • normal","19 • proche","20 • très proche"},18,false));
        p.addView(section("Guidage"));p.addView(choiceRow("Tolérance hors tracé","offroute_m",new int[]{25,35,45,60,80},new String[]{"25 m • strict","35 m • précis","45 m • équilibré","60 m • urbain","80 m • GPS difficile"},45,false));p.addView(choiceRow("Épaisseur du tracé","route_width",new int[]{6,8,10,12,14,16},new String[]{"6 • fin","8","10 • normal","12","14","16 • massif"},10,false));p.addView(toggleRow("Distance restante","Métrique visible sur la carte.","show_remaining",true,()->{if("map".equals(selectedTab))showTab("map",false);}));p.addView(toggleRow("Progression en %","Affiche l’avancement de la tournée.","show_progress",true,()->{if("map".equals(selectedTab))showTab("map",false);}));p.addView(toggleRow("Ajuster la carte au départ","Cadre automatiquement la tournée au lancement.","fit_route_start",true,()->{}));
        p.addView(section("Enregistrement GPS"));p.addView(choiceRow("Précision GPS maximale","record_accuracy",new int[]{20,30,45,60,80},new String[]{"20 m • exigeant","30 m","45 m • normal","60 m","80 m • permissif"},45,false));p.addView(choiceRow("Espacement minimum","record_spacing",new int[]{1,2,3,5,8},new String[]{"1 m • très dense","2 m • normal","3 m","5 m","8 m • léger"},2,false));p.addView(choiceRow("Sauvegarde du brouillon","draft_seconds",new int[]{5,10,15,30,60},new String[]{"5 s","10 s","15 s • normal","30 s","60 s"},15,false));p.addView(toggleRow("Garder l’écran allumé","Évite la veille pendant une tournée.","keep_screen",true,this::applyRuntimePrefs));
        p.addView(section("GPX"));p.addView(toggleRow("Recalage routier des imports","Peut améliorer un GPX externe bruité. Jamais imposé aux traces enregistrées par Routix.","gpx_match_roads",true,()->{}));TextView lab=pill("Ouvrir GPX Lab →",accent);lab.setOnClickListener(v->showTab("gpxlab",true));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(50));lp.topMargin=dp(8);p.addView(lab,lp);
        p.addView(section("Stockage"));p.addView(infoCard("Copie durable automatique","Téléchargements/Routix • les tournées finalisées restent récupérables après réinstallation quand Android l’autorise."));sv.addView(p);return sv;
    }

    private View mapStyleRow(){String current=prefs.getString("map_style","apple_dark");String label="Apple sombre";if("apple_light".equals(current))label="Apple clair";else if("terrain".equals(current))label="Terrain";else if("osm".equals(current))label="OpenStreetMap";LinearLayout row=settingsRow("Style de carte",label);row.setOnClickListener(v->{String[] labels={"Apple sombre","Apple clair","Terrain","OpenStreetMap"};String[] values={"apple_dark","apple_light","terrain","osm"};new AlertDialog.Builder(this).setTitle("Style de carte").setItems(labels,(d,w)->{prefs.edit().putString("map_style",values[w]).apply();applyMapStyle();showTab("settings",false);}).show();});return row;}
    private View choiceRow(String title,String key,int[] values,String[] labels,int def,boolean rebuild){int cur=prefs.getInt(key,def),idx=0;for(int i=0;i<values.length;i++)if(values[i]==cur){idx=i;break;}LinearLayout row=settingsRow(title,labels[idx]);row.setOnClickListener(v->new AlertDialog.Builder(this).setTitle(title).setItems(labels,(d,w)->{prefs.edit().putInt(key,values[w]).apply();if(rebuild)rebuildChrome();showTab("settings",false);}).show());return row;}
    private LinearLayout settingsRow(String title,String value){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(14),dp(12),dp(12),dp(12));row.setBackground(glass(SURFACE,20));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.addView(text(title,14,Typeface.BOLD,TEXT));tx.addView(text(value,11,Typeface.NORMAL,MUTED));row.addView(tx,new LinearLayout.LayoutParams(0,-2,1));TextView arrow=text("›",24,Typeface.NORMAL,MUTED);row.addView(arrow,new LinearLayout.LayoutParams(dp(26),-2));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(8);row.setLayoutParams(lp);return row;}
    private View toggleRow(String title,String sub,String key,boolean def,Runnable changed){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(14),dp(12),dp(12),dp(12));row.setBackground(glass(SURFACE,20));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.addView(text(title,14,Typeface.BOLD,TEXT));tx.addView(text(sub,11,Typeface.NORMAL,MUTED));row.addView(tx,new LinearLayout.LayoutParams(0,-2,1));TextView state=toggleCapsule(prefs.getBoolean(key,def));row.addView(state,new LinearLayout.LayoutParams(dp(54),dp(32)));row.setOnClickListener(v->{press(v);boolean on=!prefs.getBoolean(key,def);prefs.edit().putBoolean(key,on).apply();state.setText(on?"ON":"OFF");state.setTextColor(on?BG:MUTED);state.setBackground(glass(on?accent:SURFACE2,16));if(changed!=null)changed.run();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(8);row.setLayoutParams(lp);return row;}
    private TextView toggleCapsule(boolean on){TextView t=text(on?"ON":"OFF",10,Typeface.BOLD,on?BG:MUTED);t.setGravity(Gravity.CENTER);t.setBackground(glass(on?accent:SURFACE2,16));return t;}

    private void startRecording(){recordingPoints.clear();recordingEvents.clear();recordedDistance=0;paused=false;pausedTotal=0;recordingStarted=System.currentTimeMillis();recording=true;if(lastLocation!=null)addRecordingFix(lastLocation,true);showTab("record",false);}
    private void finishRecording(){if(recordingPoints.size()<2){toast("Pas assez de points GPS");return;}recording=false;paused=false;setFlagEnabled(false);toast("Optimisation du tracé…");List<RouteStore.Point> p=new ArrayList<>(recordingPoints);List<RouteStore.Event> e=new ArrayList<>(recordingEvents);long started=recordingStarted;new Thread(()->{File f=store.createRoute(p,e,started);store.clearDraft();runOnUiThread(()->{recordingPoints.clear();recordingEvents.clear();recordedDistance=0;toast(f==null?"Sauvegarde impossible":"Tournée sauvegardée");if(f!=null)prefs.edit().putString("gpx_lab_file",f.getName()).apply();showTab("routes",false);});},"routix-save").start();}
    private void togglePause(){if(!recording)return;if(!paused){paused=true;pauseStarted=System.currentTimeMillis();}else{paused=false;pausedTotal+=System.currentTimeMillis()-pauseStarted;if(lastLocation!=null)addRecordingFix(lastLocation,true);}showTab("record",false);}
    private void addEvent(String type,String label){if(!recording||paused||lastLocation==null){toast("Enregistrement GPS requis");return;}recordingEvents.add(new RouteStore.Event(type,label,lastLocation.getLatitude(),lastLocation.getLongitude(),System.currentTimeMillis(),lastLocation.hasAccuracy()?lastLocation.getAccuracy():0));press("REVERSE".equals(type)?reverseButton:twoSidesButton);refreshRecord();}
    private void addRecordingFix(Location l,boolean force){if(!recording||paused||l==null)return;if(l.hasAccuracy()&&l.getAccuracy()>prefs.getInt("record_accuracy",45))return;RouteStore.Point p=new RouteStore.Point(l.getLatitude(),l.getLongitude(),l.getTime()>0?l.getTime():System.currentTimeMillis(),l.hasAccuracy()?l.getAccuracy():0);if(!recordingPoints.isEmpty()){RouteStore.Point prev=recordingPoints.get(recordingPoints.size()-1);double d=RouteNormalizer.distanceM(prev,p);if(!force&&d<prefs.getInt("record_spacing",2))return;if(d<250)recordedDistance+=d;}recordingPoints.add(p);if(System.currentTimeMillis()-lastDraftAt>prefs.getInt("draft_seconds",15)*1000L){lastDraftAt=System.currentTimeMillis();store.saveDraft(recordingPoints,recordingEvents,recordingStarted);}refreshRecord();}
    private void refreshRecord(){if(recordDistance!=null)recordDistance.setText(formatDistance(recordedDistance)+"\nDISTANCE");if(recordPoints!=null)recordPoints.setText(recordingPoints.size()+"\nPOINTS");if(recordEvents!=null)recordEvents.setText(recordingEvents.size()+"\nREPÈRES");}
    private void setFlagEnabled(boolean on){for(TextView t:new TextView[]{reverseButton,twoSidesButton,pauseButton})if(t!=null){t.setEnabled(on);t.setAlpha(on?1:.4f);}}
    private void offerDraftRecovery(){RouteStore.Summary d=store.draftSummary();new AlertDialog.Builder(this).setTitle("Tournée interrompue").setMessage(d.points.size()+" points peuvent être récupérés.").setNegativeButton("Ignorer",(x,w)->store.clearDraft()).setPositiveButton("Récupérer",(x,w)->{recordingPoints.clear();recordingPoints.addAll(d.points);recordingEvents.clear();recordingEvents.addAll(d.events);recordedDistance=d.distanceM;recordingStarted=d.firstTime>0?d.firstTime:System.currentTimeMillis();recording=true;paused=false;showTab("record",true);}).show();}

    private void importGpx(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,IMPORT_GPX);}
    @Override protected void onActivityResult(int r,int result,Intent data){super.onActivityResult(r,result,data);if(r==IMPORT_GPX&&result==RESULT_OK&&data!=null&&data.getData()!=null){Uri u=data.getData();toast("Analyse du GPX…");new Thread(()->{File f=store.importGpx(u);runOnUiThread(()->{toast(f==null?"Import impossible":"GPX importé et optimisé");if(f!=null)prefs.edit().putString("gpx_lab_file",f.getName()).apply();showTab(f==null?"routes":"gpxlab",false);});},"routix-import").start();}}

    private void startGuidance(RouteStore.Summary s){if(s==null||s.points.size()<2)return;List<GuidanceEngine.Point> p=new ArrayList<>();for(RouteStore.Point q:s.points)p.add(new GuidanceEngine.Point(q.lat,q.lon));List<GuidanceEngine.Event> e=new ArrayList<>();for(RouteStore.Event q:s.events)e.add(new GuidanceEngine.Event(q.type,q.label,q.lat,q.lon));guidance=new GuidanceEngine(p,e);guidance.setOffRouteThreshold(prefs.getInt("offroute_m",45));guidingRoute=s;guiding=true;if(lastLocation!=null)guidance.reposition(lastLocation.getLatitude(),lastLocation.getLongitude());showTab("map",true);drawRemaining(null);if(prefs.getBoolean("fit_route_start",true))fitRoute(s);}
    private void drawRemaining(GuidanceEngine.State state){if(!guiding||guidingRoute==null)return;boolean erase=prefs.getBoolean("erase_passed",true);int start=!erase||state==null?0:Math.max(0,Math.min(guidingRoute.points.size()-2,state.nearestIndex));List<GeoPoint> pts=new ArrayList<>();if(state!=null&&erase&&Double.isFinite(state.position.lat))pts.add(new GeoPoint(state.position.lat,state.position.lon));for(int i=start+(erase?1:0);i<guidingRoute.points.size();i++){RouteStore.Point p=guidingRoute.points.get(i);pts.add(new GeoPoint(p.lat,p.lon));}remainingLine.setPoints(pts);remainingLine.getOutlinePaint().setColor(accent);remainingLine.getOutlinePaint().setStrokeWidth(dp(prefs.getInt("route_width",10)));if(prefs.getBoolean("route_arrows",true))routeArrows.setPoints(pts);else routeArrows.setPoints(new ArrayList<>());map.invalidate();}
    private void fitRoute(RouteStore.Summary s){double n=-90,so=90,e=-180,w=180;for(RouteStore.Point p:s.points){n=Math.max(n,p.lat);so=Math.min(so,p.lat);e=Math.max(e,p.lon);w=Math.min(w,p.lon);}BoundingBox box=new BoundingBox(n,e,so,w);map.post(()->map.zoomToBoundingBox(box,true,dp(72)));}

    @Override public void onLocationChanged(@NonNull Location l){lastLocation=l;if(headerSpeed!=null)headerSpeed.update(l);addRecordingFix(l,false);if(guiding&&guidance!=null){GuidanceEngine.State s=guidance.update(l.getLatitude(),l.getLongitude(),l.getTime()>0?l.getTime():System.currentTimeMillis(),l.hasAccuracy()?l.getAccuracy():8);drawRemaining(s);if(guideDistance!=null)guideDistance.setText(formatDistance(s.remainingM)+"\nRESTANT");if(guideProgress!=null)guideProgress.setText(s.progressPercent+" %\nPROGRESSION");if(guideTitle!=null)guideTitle.setText(s.finished?"Tournée terminée":s.offRoute?"Rejoins le tracé":"Suis les flèches");}}
    private void ensureLocation(){if(ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){ActivityCompat.requestPermissions(this,new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},LOCATION_PERMISSION);return;}try{me.enableMyLocation();lm.requestLocationUpdates(LocationManager.GPS_PROVIDER,1000,1.5f,this);if(lm.isProviderEnabled(LocationManager.NETWORK_PROVIDER))lm.requestLocationUpdates(LocationManager.NETWORK_PROVIDER,2500,5,this);}catch(Exception ignored){}}
    @Override public void onRequestPermissionsResult(int r,@NonNull String[] p,@NonNull int[] g){super.onRequestPermissionsResult(r,p,g);if(r==LOCATION_PERMISSION&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)ensureLocation();}
    private void recenter(){if(lastLocation==null){toast("GPS en attente");return;}map.getController().animateTo(new GeoPoint(lastLocation.getLatitude(),lastLocation.getLongitude()));map.getController().setZoom(prefs.getInt("recenter_zoom",18)+.2);}

    private LinearLayout page(String title,String sub){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);int pad=prefs.getBoolean("compact_ui",false)?13:17;p.setPadding(dp(pad),dp(prefs.getBoolean("compact_ui",false)?12:18),dp(pad),dp(24));p.addView(text(title,29,Typeface.BOLD,TEXT));TextView s=text(sub,12,Typeface.NORMAL,MUTED);s.setPadding(0,dp(4),0,dp(14));p.addView(s);return p;}
    private TextView section(String s){TextView t=text(s.toUpperCase(Locale.ROOT),10,Typeface.BOLD,accent);t.setPadding(0,dp(20),0,dp(8));return t;}
    private TextView text(String s,float size,int style,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setTypeface(Typeface.create("sans-serif",style));t.setIncludeFontPadding(false);return t;}
    private TextView pill(String s,int color){TextView t=text(s,13,Typeface.BOLD,(color==accent||color==GREEN||color==PEACH||color==RED)?BG:TEXT);t.setGravity(Gravity.CENTER);t.setBackground(glass(color,19));t.setElevation(dp(2));return t;}
    private TextView metric(String value,String label){TextView t=text(value+"\n"+label,13,Typeface.BOLD,TEXT);t.setGravity(Gravity.CENTER);t.setBackground(glass(SURFACE,19));return t;}
    private TextView bigMetric(String value,String label,int color){TextView t=text(value+"\n"+label,18,Typeface.BOLD,TEXT);t.setGravity(Gravity.CENTER);t.setBackground(glass(Color.argb(160,Color.red(color),Color.green(color),Color.blue(color)),24));return t;}
    private TextView icon(String s){TextView t=text(s,20,Typeface.BOLD,TEXT);t.setGravity(Gravity.CENTER);t.setBackground(glass(SURFACE2,17));return t;}
    private TextView infoCard(String title,String body){TextView t=text(title+"\n"+body,12,Typeface.NORMAL,MUTED);t.setTypeface(Typeface.create("sans-serif",Typeface.NORMAL));t.setPadding(dp(14),dp(12),dp(14),dp(12));t.setBackground(glass(SURFACE,20));return t;}
    private View stage(String number,String title,String sub,int color){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(12),dp(10),dp(12),dp(10));r.setBackground(glass(SURFACE,18));TextView n=text(number,12,Typeface.BOLD,color);n.setGravity(Gravity.CENTER);n.setBackground(glass(SURFACE2,14));r.addView(n,new LinearLayout.LayoutParams(dp(42),dp(42)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.setPadding(dp(11),0,0,0);tx.addView(text(title,13,Typeface.BOLD,TEXT));tx.addView(text(sub,11,Typeface.NORMAL,MUTED));r.addView(tx,new LinearLayout.LayoutParams(0,-2,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(7);r.setLayoutParams(lp);return r;}
    private GradientDrawable glass(int color,float radius){int a=prefs==null?82:prefs.getInt("glass_alpha",82);int aa=Math.max(35,Math.min(100,a))*255/100;int c1=Color.argb(Math.min(255,aa+18),Color.red(color),Color.green(color),Color.blue(color));int c2=Color.argb(aa,Color.red(color),Color.green(color),Color.blue(color));GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{c1,c2});g.setCornerRadius(dp(radius));g.setStroke(dp(1),Color.argb(42,255,255,255));return g;}
    private void press(View v){if(v==null)return;if(prefs.getBoolean("haptics",true))v.performHapticFeedback(HapticFeedbackConstants.KEYBOARD_TAP);if(prefs.getBoolean("animations",true))v.animate().scaleX(.94f).scaleY(.94f).setDuration(70).withEndAction(()->v.animate().scaleX(1).scaleY(1).setDuration(150).start()).start();}
    private int animDuration(){return prefs.getInt("anim_speed",220);}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    private int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);}
    private static String formatDistance(double m){return m<1000?Math.round(m)+" m":String.format(Locale.FRANCE,"%.1f km",m/1000d);}
    private static String formatMinutes(int m){return String.format(Locale.FRANCE,"%dh%02d",m/60,m%60);}

    private void rebuildChrome(){if(root==null)return;if(topBar!=null)root.removeView(topBar);if(dock!=null)root.removeView(dock);topBar=buildTopBar();dock=buildDock();root.addView(topBar);root.addView(dock);topBar.bringToFront();dock.bringToFront();contentHost.bringToFront();dock.bringToFront();updateDock();positionChrome();applyRuntimePrefs();}
    private void applyRuntimePrefs(){if(prefs.getBoolean("keep_screen",true))getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);else getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);if(mapLogo!=null)mapLogo.setVisibility("map".equals(selectedTab)&&prefs.getBoolean("map_logo",true)?View.VISIBLE:View.GONE);if(headerSpeed!=null)headerSpeed.setVisibility(prefs.getBoolean("show_speed",true)?View.VISIBLE:View.GONE);}
    private void positionChrome(){if(root==null||topBar==null||dock==null||contentHost==null)return;boolean compact=prefs.getBoolean("compact_ui",false);int top=systemTop+dp(8),bottom=systemBottom+dp(8),topH=dp(compact?58:64),dockH=dp(compact?62:70);FrameLayout.LayoutParams hp=new FrameLayout.LayoutParams(-1,topH,Gravity.TOP);hp.setMargins(dp(10),top,dp(10),0);topBar.setLayoutParams(hp);FrameLayout.LayoutParams dpv=new FrameLayout.LayoutParams(-1,dockH,Gravity.BOTTOM);dpv.setMargins(dp(10),0,dp(10),bottom);dock.setLayoutParams(dpv);if(mapLogo!=null){FrameLayout.LayoutParams ml=new FrameLayout.LayoutParams(dp(52),dp(52),Gravity.TOP|Gravity.START);ml.setMargins(dp(14),top+topH+dp(10),0,0);mapLogo.setLayoutParams(ml);}if("map".equals(selectedTab)){FrameLayout.LayoutParams cp=new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM);cp.setMargins(dp(10),0,dp(10),bottom+dockH+dp(8));contentHost.setLayoutParams(cp);}else{FrameLayout.LayoutParams cp=new FrameLayout.LayoutParams(-1,-1);cp.setMargins(0,top+topH+dp(8),0,bottom+dockH+dp(8));contentHost.setLayoutParams(cp);}}

    @Override protected void onResume(){super.onResume();if(map!=null)map.onResume();}
    @Override protected void onPause(){super.onPause();if(map!=null)map.onPause();if(recording)store.saveDraft(recordingPoints,recordingEvents,recordingStarted);}
    @Override protected void onDestroy(){try{lm.removeUpdates(this);}catch(Exception ignored){}if(me!=null)me.disableMyLocation();if(map!=null)map.onDetach();super.onDestroy();}
    @Override public void onProviderEnabled(@NonNull String provider){} @Override public void onProviderDisabled(@NonNull String provider){}
}
